const fs = require('fs');

const dataStr = fs.readFileSync('src/data/mockData.ts', 'utf-8');

const newActivities = `  {
    id: "sin-bird-paradise",
    name: "Bird Paradise Tickets | Mandai Wildlife Reserve",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Zoos & Aquariums",
    rating: 4.8,
    reviewsCount: 1250,
    price: 35.0,
    imageUrl: "https://images.unsplash.com/photo-1549472393-5ce25eb5fbdb?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Immerse yourself in a symphony of colours at Asia's largest bird park.",
    highlights: ["Walk-through aviaries", "Avian presentations", "Diverse bird species"],
    included: ["Admission ticket"],
    duration: "3-4 hours",
    openingHours: "Daily: 09:00 - 18:00",
  },
  {
    id: "sin-flyer",
    name: "Singapore Flyer Tickets",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Observation Decks",
    rating: 4.6,
    reviewsCount: 8500,
    price: 30.0,
    imageUrl: "https://images.unsplash.com/photo-1520038410233-7141be7e6f97?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Enjoy panoramic views of Marina Bay and beyond from Asia's largest giant observation wheel.",
    highlights: ["360-degree city views", "30-minute flight", "Time Capsule entry"],
    included: ["Flight ticket", "Time Capsule access"],
    duration: "1 hour",
    openingHours: "Daily: 10:00 - 22:00",
  },
  {
    id: "sin-wings-time",
    name: "Wings Of Time Tickets, Singapore",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Shows & Events",
    rating: 4.5,
    reviewsCount: 5400,
    price: 15.0,
    imageUrl: "https://images.unsplash.com/photo-1598463959828-0902c39d48ea?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "End your day at Sentosa with the award-winning multi-sensory night show.",
    highlights: ["Laser and fire effects", "Water display", "Epic storyline"],
    included: ["Show ticket"],
    duration: "20 minutes",
    openingHours: "Daily: 19:40 & 20:40",
  },
  {
    id: "sin-mbs-skypark",
    name: "Marina Bay Sands Skypark Observation Deck Tickets, Singapore",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Observation Decks",
    rating: 4.7,
    reviewsCount: 11200,
    price: 25.0,
    imageUrl: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Take in stunning views of Singapore from the iconic Marina Bay Sands Skypark.",
    highlights: ["Panoramic views of the city", "Gardens by the Bay views", "Great photo opportunities"],
    included: ["Admission ticket"],
    duration: "1-2 hours",
    openingHours: "Daily: 11:00 - 21:00",
  },
  {
    id: "sin-night-safari",
    name: "Singapore Night Safari Tickets with Tram Ride | Mandai Wildlife Reserve",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Zoos & Aquariums",
    rating: 4.8,
    reviewsCount: 14300,
    price: 45.0,
    imageUrl: "https://images.unsplash.com/photo-1534567059665-cb52ded2f1a6?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Experience the world's first nocturnal wildlife park and explore it via a guided tram ride.",
    highlights: ["Guided tram ride", "Creatures of the Night show", "Walking trails"],
    included: ["Admission ticket", "Tram ride"],
    duration: "3-4 hours",
    openingHours: "Daily: 19:15 - 00:00",
  },
  {
    id: "sin-oceanarium",
    name: "Singapore Oceanarium Tickets",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Zoos & Aquariums",
    rating: 4.7,
    reviewsCount: 9600,
    price: 40.0,
    imageUrl: "https://images.unsplash.com/photo-1549472393-5ce25eb5fbdb?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Explore the fascinating marine realm of S.E.A. Aquarium, home to more than 100,000 marine animals.",
    highlights: ["Huge open ocean tank", "Shark seas", "Interactive touch pool"],
    included: ["Admission ticket"],
    duration: "2-3 hours",
    openingHours: "Daily: 10:00 - 17:00",
  },
  {
    id: "sin-madame-tussauds",
    name: "Madame Tussauds Singapore Tickets",
    location: "Singapore",
    city: "Singapore",
    region: "Asia",
    category: "Museums",
    rating: 4.4,
    reviewsCount: 5200,
    price: 28.0,
    imageUrl: "https://images.unsplash.com/photo-1579294970420-1e592652a925?auto=format&fit=crop&q=80&w=800",
    isPopular: false,
    description: "Mingle with your favorite celebrities and experience the Spirit of Singapore boat ride.",
    highlights: ["Lifelike wax figures", "Spirit of Singapore boat ride", "Marvel Universe 4D"],
    included: ["Admission ticket"],
    duration: "2-3 hours",
    openingHours: "Daily: 10:00 - 18:00",
  },
  {
    id: "hkt-carnival-magic",
    name: "Carnival Magic Tickets, Phuket",
    location: "Phuket, Thailand",
    city: "Phuket",
    region: "Asia",
    category: "Theme Parks",
    rating: 4.8,
    reviewsCount: 2100,
    price: 65.0,
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Experience the magic of Thai culture with stunning parades, illuminations, and a grand buffet.",
    highlights: ["River Palace Parade", "Kingdom of Lights", "Carnival Fun Fair"],
    included: ["Admission ticket", "Show ticket"],
    duration: "4-5 hours",
    openingHours: "Mon, Wed, Sat: 17:30 - 23:30",
  },
  {
    id: "bkk-ancient-city",
    name: "Ancient City",
    location: "Bangkok, Thailand",
    city: "Bangkok",
    region: "Asia",
    category: "Historic Sites",
    rating: 4.7,
    reviewsCount: 4300,
    price: 22.0,
    imageUrl: "https://images.unsplash.com/photo-1598463959828-0902c39d48ea?auto=format&fit=crop&q=80&w=800",
    isPopular: false,
    description: "Explore the world's largest outdoor museum featuring scaled-down replicas of Thailand's most significant historical structures.",
    highlights: ["Replicas of famous Thai temples", "Vast outdoor area", "Rent a bicycle or golf cart"],
    included: ["Admission ticket"],
    duration: "Half day",
    openingHours: "Daily: 09:00 - 18:00",
  },
  {
    id: "bkk-erawan-museum",
    name: "Erawan Museum Tickets",
    location: "Bangkok, Thailand",
    city: "Bangkok",
    region: "Asia",
    category: "Museums",
    rating: 4.6,
    reviewsCount: 3800,
    price: 12.0,
    imageUrl: "https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&q=80&w=800",
    isPopular: false,
    description: "Marvel at the giant three-headed elephant statue housing a fascinating museum of antiquities.",
    highlights: ["Giant three-headed elephant sculpture", "Intricate interiors", "Beautiful gardens"],
    included: ["Admission ticket"],
    duration: "1-2 hours",
    openingHours: "Daily: 09:00 - 18:00",
  },
  {
    id: "bkk-siam-amazing-park",
    name: "Siam Amazing Park Tickets, Bangkok",
    location: "Bangkok, Thailand",
    city: "Bangkok",
    region: "Asia",
    category: "Theme Parks",
    rating: 4.5,
    reviewsCount: 6100,
    price: 25.0,
    imageUrl: "https://images.unsplash.com/photo-1520038410233-7141be7e6f97?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Enjoy a fun-filled day at one of Southeast Asia's largest theme and water parks.",
    highlights: ["Giant wave pool", "Thrilling roller coasters", "Family-friendly rides"],
    included: ["Admission ticket", "Access to water park and amusement park"],
    duration: "Full day",
    openingHours: "Daily: 10:00 - 18:00",
  },
  {
    id: "hkt-aquaria",
    name: "Aquaria Phuket Tickets",
    location: "Phuket, Thailand",
    city: "Phuket",
    region: "Asia",
    category: "Zoos & Aquariums",
    rating: 4.6,
    reviewsCount: 2900,
    price: 26.0,
    imageUrl: "https://images.unsplash.com/photo-1549472393-5ce25eb5fbdb?auto=format&fit=crop&q=80&w=800",
    isPopular: false,
    description: "Discover the wonders of the ocean at the largest aquarium in Thailand.",
    highlights: ["Over 25,000 animals", "Interactive zones", "Underwater dining experience (optional)"],
    included: ["Admission ticket"],
    duration: "2-3 hours",
    openingHours: "Daily: 10:30 - 18:00",
  },
  {
    id: "bkk-madame-tussauds",
    name: "Madame Tussauds Bangkok Tickets",
    location: "Bangkok, Thailand",
    city: "Bangkok",
    region: "Asia",
    category: "Museums",
    rating: 4.4,
    reviewsCount: 4100,
    price: 24.0,
    imageUrl: "https://images.unsplash.com/photo-1579294970420-1e592652a925?auto=format&fit=crop&q=80&w=800",
    isPopular: false,
    description: "Get up close and take selfies with lifelike wax figures of global icons and celebrities.",
    highlights: ["A-list celebrities", "Historical figures", "Interactive exhibits"],
    included: ["Admission ticket"],
    duration: "1-2 hours",
    openingHours: "Daily: 10:00 - 20:00",
  },
  {
    id: "hkt-dolphin-show",
    name: "Phuket Dolphin Show Ticket",
    location: "Phuket, Thailand",
    city: "Phuket",
    region: "Asia",
    category: "Shows & Events",
    rating: 4.5,
    reviewsCount: 3200,
    price: 20.0,
    imageUrl: "https://images.unsplash.com/photo-1534567059665-cb52ded2f1a6?auto=format&fit=crop&q=80&w=800",
    isPopular: false,
    description: "Be entertained by the incredible intelligence and agility of dolphins at this family-friendly show.",
    highlights: ["Dolphin acrobatic displays", "Seal performances", "Photo opportunities"],
    included: ["Show ticket"],
    duration: "45 minutes",
    openingHours: "Tue-Sun: 11:00, 14:00, 17:00",
  },
  {
    id: "pat-colosseum-show",
    name: "Colosseum Show Pattaya Tickets",
    location: "Pattaya, Thailand",
    city: "Pattaya",
    region: "Asia",
    category: "Shows & Events",
    rating: 4.7,
    reviewsCount: 5800,
    price: 18.0,
    imageUrl: "https://images.unsplash.com/photo-1598463959828-0902c39d48ea?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
    description: "Experience Thailand's largest and most spectacular cabaret show featuring dazzling costumes and sets.",
    highlights: ["Extravagant cabaret performances", "Spectacular costumes", "State-of-the-art theater"],
    included: ["Show ticket"],
    duration: "75 minutes",
    openingHours: "Daily: 18:00, 19:30, 21:00",
  }`;

// Find the end of POPULAR_ATTRACTIONS array which is before DESTINATIONS
const targetStr = `export const DESTINATIONS`;
const destIndex = dataStr.indexOf(targetStr);

if (destIndex !== -1) {
  // Find the last '];' before DESTINATIONS
  const arrEndIndex = dataStr.lastIndexOf('];', destIndex);
  
  if (arrEndIndex !== -1) {
    const updatedStr = dataStr.slice(0, arrEndIndex) + ',\n' + newActivities + '\n' + dataStr.slice(arrEndIndex);
    fs.writeFileSync('src/data/mockData.ts', updatedStr);
    console.log("Successfully injected activities.");
  } else {
    console.log("Could not find end of POPULAR_ATTRACTIONS array.");
  }
} else {
  console.log("Could not find DESTINATIONS.");
}
