const fs = require('fs');
let code = fs.readFileSync('src/admin/pages/Inventory.tsx', 'utf8');

const replacement = `const TIMEZONES = [
  { value: "Etc/GMT+12", label: "(UTC-12:00) International Date Line West" },
  { value: "Etc/GMT+11", label: "(UTC-11:00) Coordinated Universal Time-11" },
  { value: "Pacific/Honolulu", label: "(UTC-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(UTC-09:00) Alaska" },
  { value: "America/Santa_Isabel", label: "(UTC-08:00) Baja California" },
  { value: "America/Los_Angeles", label: "(UTC-08:00) Pacific Time (US and Canada)" },
  { value: "America/Phoenix", label: "(UTC-07:00) Arizona" },
  { value: "America/Denver", label: "(UTC-07:00) Mountain Time (US and Canada)" },
  { value: "America/Guatemala", label: "(UTC-06:00) Central America" },
  { value: "America/Chihuahua", label: "(UTC-07:00) Chihuahua, La Paz, Mazatlan" },
  { value: "America/Chicago", label: "(UTC-06:00) Central Time (US and Canada)" },
  { value: "America/Mexico_City", label: "(UTC-06:00) Guadalajara, Mexico City, Monterey" },
  { value: "America/Regina", label: "(UTC-06:00) Saskatchewan" },
  { value: "America/Indiana/Indianapolis", label: "(UTC-05:00) Indiana (East)" },
  { value: "America/Bogota", label: "(UTC-05:00) Bogota, Lima, Quito" },
  { value: "America/New_York", label: "(UTC-05:00) Eastern Time (US and Canada)" },
  { value: "America/Cuiaba", label: "(UTC-04:00) Cuiaba" },
  { value: "America/Halifax", label: "(UTC-04:00) Atlantic Time (Canada)" },
  { value: "America/Santiago", label: "(UTC-04:00) Santiago" },
  { value: "America/La_Paz", label: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan" },
  { value: "America/Caracas", label: "(UTC-04:30) Caracas" },
  { value: "America/Asuncion", label: "(UTC-04:00) Asuncion" },
  { value: "America/St_Johns", label: "(UTC-03:30) Newfoundland" },
  { value: "America/Sao_Paulo", label: "(UTC-03:00) Brasilia" },
  { value: "America/Cayenne", label: "(UTC-03:00) Cayenne, Fortaleza" },
  { value: "America/Montevideo", label: "(UTC-03:00) Montevideo" },
  { value: "America/Argentina/Buenos_Aires", label: "(UTC-03:00) Buenos Aires" },
  { value: "Etc/GMT+2", label: "(UTC-02:00) Coordinated Universal Time-2" },
  { value: "America/Godthab", label: "(UTC-03:00) Greenland" },
  { value: "Atlantic/Azores", label: "(UTC-01:00) Azores" },
  { value: "Atlantic/Cape_Verde", label: "(UTC-01:00) Cape Verde" },
  { value: "Europe/London", label: "(UTC+00:00) Dublin, Edinburgh, Lisbon, London" },
  { value: "Atlantic/Reykjavik", label: "(UTC+00:00) Monrovia, Reykjavik" },
  { value: "Etc/GMT", label: "(UTC+00:00) Coordinated Universal Time" },
  { value: "Africa/Casablanca", label: "(UTC+00:00) Casablanca" },
  { value: "Europe/Berlin", label: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
  { value: "Europe/Budapest", label: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" },
  { value: "Europe/Warsaw", label: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb" },
  { value: "Europe/Paris", label: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris" },
  { value: "Africa/Windhoek", label: "(UTC+01:00) Windhoek" },
  { value: "Africa/Lagos", label: "(UTC+01:00) West Central Africa" },
  { value: "Africa/Cairo", label: "(UTC+02:00) Cairo" },
  { value: "Asia/Beirut", label: "(UTC+02:00) Beirut" },
  { value: "Africa/Johannesburg", label: "(UTC+02:00) Harare, Pretoria" },
  { value: "Asia/Jerusalem", label: "(UTC+02:00) Jerusalem" },
  { value: "Europe/Kiev", label: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
  { value: "Africa/Nairobi", label: "(UTC+03:00) Nairobi" },
  { value: "Europe/Moscow", label: "(UTC+04:00) Moscow, St. Petersburg, Volgograd" },
  { value: "Asia/Baghdad", label: "(UTC+03:00) Baghdad" },
  { value: "Europe/Istanbul", label: "(UTC+02:00) Athens, Bucharest, Istanbul" },
  { value: "Asia/Damascus", label: "(UTC+02:00) Damascus" },
  { value: "Asia/Riyadh", label: "(UTC+03:00) Kuwait, Riyadh" },
  { value: "Europe/Minsk", label: "(UTC+03:00) Minsk" },
  { value: "Asia/Amman", label: "(UTC+02:00) Amman" },
  { value: "Asia/Tehran", label: "(UTC+03:30) Tehran" },
  { value: "Asia/Yerevan", label: "(UTC+04:00) Yerevan" },
  { value: "Asia/Baku", label: "(UTC+04:00) Baku" },
  { value: "Asia/Dubai", label: "(UTC+04:00) Abu Dhabi, Muscat" },
  { value: "Asia/Tbilisi", label: "(UTC+04:00) Tbilisi" },
  { value: "Indian/Mauritius", label: "(UTC+04:00) Port Louis" },
  { value: "Asia/Kabul", label: "(UTC+04:30) Kabul" },
  { value: "Asia/Tashkent", label: "(UTC+05:00) Tashkent" },
  { value: "Asia/Almaty", label: "(UTC+06:00) Astana" },
  { value: "Asia/Karachi", label: "(UTC+05:00) Islamabad, Karachi" },
  { value: "Asia/Yekaterinburg", label: "(UTC+06:00) Yekaterinburg" },
  { value: "Asia/Kolkata", label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
  { value: "Asia/Colombo", label: "(UTC+05:30) Sri Jayewardenepura Kotte" },
  { value: "Asia/Kathmandu", label: "(UTC+05:45) Kathmandu" },
  { value: "Asia/Dhaka", label: "(UTC+06:00) Dhaka" },
  { value: "Asia/Yangon", label: "(UTC+06:30) Yangon" },
  { value: "Asia/Bangkok", label: "(UTC+07:00) Bangkok, Hanoi, Jakarta" },
  { value: "Asia/Novosibirsk", label: "(UTC+07:00) Novosibirsk" },
  { value: "Asia/Krasnoyarsk", label: "(UTC+08:00) Krasnoyarsk" },
  { value: "Asia/Ulaanbaatar", label: "(UTC+08:00) Ulaanbaatar" },
  { value: "Asia/Shanghai", label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
  { value: "Asia/Taipei", label: "(UTC+08:00) Taipei" },
  { value: "Australia/Perth", label: "(UTC+08:00) Perth" },
  { value: "Asia/Irkutsk", label: "(UTC+09:00) Irkutsk" },
  { value: "Asia/Singapore", label: "(UTC+08:00) Kuala Lumpur, Singapore" },
  { value: "Asia/Yakutsk", label: "(UTC+10:00) Yakutsk" },
  { value: "Asia/Seoul", label: "(UTC+09:00) Seoul" },
  { value: "Asia/Tokyo", label: "(UTC+09:00) Osaka, Sapporo, Tokyo" },
  { value: "Australia/Adelaide", label: "(UTC+09:30) Adelaide" },
  { value: "Australia/Darwin", label: "(UTC+09:30) Darwin" },
  { value: "Asia/Vladivostok", label: "(UTC+11:00) Vladivostok" },
  { value: "Australia/Hobart", label: "(UTC+10:00) Hobart" },
  { value: "Pacific/Port_Moresby", label: "(UTC+10:00) Guam, Port Moresby" },
  { value: "Australia/Sydney", label: "(UTC+10:00) Canberra, Melbourne, Sydney" },
  { value: "Australia/Brisbane", label: "(UTC+10:00) Brisbane" },
  { value: "Asia/Magadan", label: "(UTC+12:00) Magadan" },
  { value: "Pacific/Guadalcanal", label: "(UTC+11:00) Solomon Islands, New Caledonia" },
  { value: "Pacific/Fiji", label: "(UTC+12:00) Fiji, Marshall Islands" },
  { value: "Etc/GMT-12", label: "(UTC+12:00) Coordinated Universal Time+12" },
  { value: "Pacific/Auckland", label: "(UTC+12:00) Auckland, Wellington" },
  { value: "Pacific/Tongatapu", label: "(UTC+13:00) Nuku'alofa" },
  { value: "Pacific/Apia", label: "(UTC+13:00) Samoa" }
];`;

code = code.replace(/const TIMEZONES = \[[\s\S]*?\];/, replacement);
fs.writeFileSync('src/admin/pages/Inventory.tsx', code);
console.log('patched');
