import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { Currency, Theme, Language } from '../types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', countryCode: 'gb', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', countryCode: 'fr', dir: 'ltr' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱', countryCode: 'nl', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', countryCode: 'es', dir: 'ltr' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱', countryCode: 'pl', dir: 'ltr' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '中文 (Simplified)', flag: '🇨🇳', countryCode: 'cn', dir: 'ltr' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', countryCode: 'it', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', countryCode: 'de', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', countryCode: 'ru', dir: 'ltr' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴', countryCode: 'ro', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', countryCode: 'sa', dir: 'rtl' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', countryCode: 'jp', dir: 'ltr' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭', countryCode: 'th', dir: 'ltr' },
];

export const CURRENCIES: Currency[] = [
  { code: 'EUR', name: 'Euro', symbol: '€', rate: 1 },
  { code: 'USD', name: 'United States Dollar', symbol: '$', rate: 1.08 },
  { code: 'GBP', name: 'British Pound', symbol: '£', rate: 0.86 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'AU$', rate: 1.63 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', rate: 1.48 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', rate: 0.98 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rate: 7.46 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rate: 11.60 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', rate: 4.30 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rate: 11.40 },
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ', rate: 3.97 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rate: 390 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rate: 1.46 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rate: 8.44 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rate: 168 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', rate: 4200 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', rate: 1.78 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rate: 5.10 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', rate: 25.10 },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$', rate: 18.20 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', rate: 90 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', rate: 39.5 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rate: 5.50 },
  { code: 'AZN', name: 'Azerbaijani manat', symbol: '₼', rate: 1.84 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', rate: 0.41 },
  { code: 'BYN', name: 'Belarusian ruble', symbol: 'Br', rate: 3.53 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', rate: 1010 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rate: 7.82 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 17400 },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', rate: 4.02 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', rate: 0.77 },
  { code: 'KRW', name: 'Korean Won', symbol: '₩', rate: 1480 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', rate: 0.33 },
  { code: 'KZT', name: 'Kazakhstani tenge', symbol: '₸', rate: 480 },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', rate: 23100 },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', rate: 3755 },
  { code: 'MOP', name: 'Macau Pataca', symbol: 'MOP$', rate: 8.70 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', rate: 0.42 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', rate: 63.4 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', rate: 301 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', rate: 3.93 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', rate: 97.5 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', rate: 4.05 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rate: 35.1 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', rate: 34.9 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rate: 27500 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', rate: 19.8 },
];

const detectLocalCurrencyCode = (): string => {
  try {
    const intlCurrency = Intl.NumberFormat().resolvedOptions().currency;
    if (intlCurrency && CURRENCIES.some(c => c.code === intlCurrency)) {
      return intlCurrency;
    }
  } catch (e) {
    console.warn('Intl currency detection error:', e);
  }

  try {
    const locale = navigator.language || (navigator.languages && navigator.languages[0]) || '';
    const uppercaseLocale = locale.toUpperCase();
    if (uppercaseLocale.includes('IN')) return 'INR';
    if (uppercaseLocale.includes('GB')) return 'GBP';
    if (uppercaseLocale.includes('AE')) return 'AED';
    if (uppercaseLocale.includes('SG')) return 'SGD';
    if (uppercaseLocale.includes('US')) return 'USD';
    
    const euroLocales = ['FR', 'DE', 'ES', 'IT', 'NL', 'BE', 'AT', 'FI', 'GR', 'IE', 'PT'];
    if (euroLocales.some(el => uppercaseLocale.includes(el))) return 'EUR';
  } catch (e) {
    console.warn('Navigator locale detection error:', e);
  }

  return 'USD';
};

interface SettingsContextType {
  currency: Currency;
  detectedLocalCurrency: Currency;
  language: Language;
  languages: Language[];
  theme: Theme;
  setCurrency: (curr: Currency) => void;
  setLanguage: (lang: Language) => void;
  setTheme: (theme: Theme) => void;
  formatPrice: (price: number, baseCurrencyCode?: string) => string;
  t: (key: string, fallback?: string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  en: {
    heroEyebrow: 'DISCOVER. DREAM. EXPLORE.',
    heroTitle1: 'Explore',
    heroTitle2: 'unforgettable',
    heroTitle3: 'experiences',
    heroTitle4: 'around the world',
    heroSubtitle: 'Handpicked destinations, unique activities and memories that last a lifetime.',
    searchPlaceholder: 'Search attractions, cities or activities...',
    searchBtn: 'Search',
    popularDestinations: 'Popular destinations',
    topRatedAttractions: 'Popular attractions',
    getTickets: 'Get tickets',
    from: 'From',
    discoverMore: 'Load More',
    whyBook: 'Why book with Tiqsey?',
    mobileTickets: 'Trusted by thousands',
    mobileTicketsSub: 'Over 12M+ happy customers',
    unbeatableValue: 'Unbeatable Value',
    unbeatableValueSub: 'Price guarantee',
    flexibleBooking: 'Flexible Booking',
    flexibleBookingSub: 'Cancel up to 24h in advance',
    navHome: 'Home',
    navHotDeals: 'Hot Deals',
    navAttractionsAndTours: 'Attractions & Museums',
    navThingsToDo: 'Things to do',
    navAboutUs: 'About Us',
    navTravelBlog: 'Travel Blog',
    navRegions: 'Regions',
    navCities: 'Destinations',
    navGoCityPass: 'City Pass',
    navFavorites: 'My Favourite',
    navSignIn: 'Sign in',
    navSignUp: 'Sign up',
    navMyAccount: 'My Account',
    trustRating: '4.8/5 Rating',
    securePayments: 'Secure Payments',
    securePaymentsSub: '100% Protection',
    instantBooking: 'Instant Booking',
    instantBookingSub: 'Get it in seconds',
    instantConfirmation: 'Instant Confirmation',
    instantConfirmationSub: 'Get e-tickets instantly',
    freeCancellation: 'Free Cancellation',
    freeCancellationSub: 'Up to 24 hours',
    bestPriceGuarantee: 'Best Price Guarantee',
    bestPriceGuaranteeSub: 'We match the price',
    secureBooking: 'Secure Booking',
    secureBookingSub: 'Your data is protected',
    specialOffers: 'Special Offers',
    limitedStock: 'Limited Stock remaining',
    exploreWorldAttractions: "Explore the world's best attractions & experiences",
    exploreWorldAttractionsSub: 'Book tickets for top attractions, tours and activities across 30+ countries.',
    adBannerHighlight: 'Book now and get up to 30% off on your next trip to top curated landmarks!',
    getBestDeals: 'Get Best Deals',
    newsletterTitle: 'Stay in the loop',
    newsletterSubtitle: 'Join our newsletter and receive a discount code for your next booking.',
    yourEmail: 'Your email address',
    subscribe: 'Subscribe',
    subscribedSuccess: 'Thank you for subscribing! Check your email for discounts.',
    regionLanguage: 'Region & Language',
    language: 'Language',
    currency: 'Currency',
    theme: 'Theme',
    wishlist: 'Wishlist',
    allRightsReserved: 'All rights reserved.',
    followUs: 'Follow Us',
    curatedSelection: 'Curated selection',
    support: 'Support',
    aboutUs: 'About Us',
    aboutTiqsey: 'About Tiqsey',
    privacyPolicy: 'Privacy Policy',
    cookiePolicy: 'Cookie Policy',
    termsAndConditions: 'Terms & Conditions',
    platform: 'Platform',
    supportAndMedia: 'Support & Media',
    myBookings: 'My Bookings',
    profile: 'My Profile',
    selectLanguage: 'Select Language',
    selectCurrency: 'Select Currency',
    searchLanguagesPlaceholder: 'Search languages...',
    searchCurrenciesPlaceholder: 'Search currencies...',
    noLanguagesFound: 'No languages found',
    noCurrenciesFound: 'No currencies found'
  },
  fr: {
    heroEyebrow: 'DÉCOUVRIR. RÊVER. EXPLORER.',
    heroTitle1: 'Explorez',
    heroTitle2: 'des expériences',
    heroTitle3: 'inoubliables',
    heroTitle4: 'à travers le monde',
    heroSubtitle: 'Destinations sélectionnées avec soin, activités uniques et souvenirs gravés à jamais.',
    searchPlaceholder: 'Rechercher des attractions, villes ou activités...',
    searchBtn: 'Rechercher',
    popularDestinations: 'Destinations populaires',
    topRatedAttractions: 'Attractions populaires',
    getTickets: 'Réserver des billets',
    from: 'À partir de',
    discoverMore: 'Charger plus',
    whyBook: 'Pourquoi réserver avec Tiqsey ?',
    mobileTickets: 'Approuvé par des milliers',
    mobileTicketsSub: 'Plus de 12M+ clients heureux',
    unbeatableValue: 'Valeur imbattable',
    unbeatableValueSub: 'Garantie du meilleur prix',
    flexibleBooking: 'Réservation Flexible',
    flexibleBookingSub: 'Annulation jusqu\'à 24h à l\'avance',
    navHome: 'Accueil',
    navHotDeals: 'Offres Chaudes',
    navAttractionsAndTours: 'Attractions & Musées',
    navThingsToDo: 'Activités',
    navAboutUs: 'À propos',
    navTravelBlog: 'Blog de voyage',
    navRegions: 'Régions',
    navCities: 'Destinations',
    navGoCityPass: 'Pass Ville',
    navFavorites: 'Mes Favoris',
    navSignIn: 'Se connecter',
    navSignUp: 'S\'inscrire',
    navMyAccount: 'Mon Compte',
    trustRating: 'Évaluation 4.8/5',
    securePayments: 'Paiements Sécurisés',
    securePaymentsSub: 'Protection à 100%',
    instantBooking: 'Réservation Instantanée',
    instantBookingSub: 'Obtenez en secondes',
    instantConfirmation: 'Confirmation Instantanée',
    instantConfirmationSub: 'E-billets immédiats',
    freeCancellation: 'Annulation Gratuite',
    freeCancellationSub: 'Jusqu\'à 24 heures',
    bestPriceGuarantee: 'Garantie Meilleur Prix',
    bestPriceGuaranteeSub: 'Alignement garanti',
    secureBooking: 'Réservation Sécurisée',
    secureBookingSub: 'Données protégées',
    specialOffers: 'Offres Spéciales',
    limitedStock: 'Stock limité restant',
    exploreWorldAttractions: 'Explorez les meilleures attractions et expériences du monde',
    exploreWorldAttractionsSub: 'Réservez des billets pour les meilleures attractions, visites et activités dans plus de 180 pays.',
    adBannerHighlight: 'Réservez maintenant et obtenez jusqu\'à 30% de réduction sur votre prochain voyage !',
    getBestDeals: 'Profiter des offres',
    newsletterTitle: 'Restez informé',
    newsletterSubtitle: 'Rejoignez notre newsletter et recevez un code de réduction pour votre prochaine réservation.',
    yourEmail: 'Votre adresse email',
    subscribe: 'S\'abonner',
    subscribedSuccess: 'Merci pour votre inscription ! Vérifiez votre boîte mail.',
    regionLanguage: 'Région et langue',
    language: 'Langue',
    currency: 'Devise',
    theme: 'Thème',
    wishlist: 'Liste d\'envies',
    allRightsReserved: 'Tous droits réservés.',
    followUs: 'Suivez-nous',
    curatedSelection: 'Sélection triée',
    support: 'Assistance',
    aboutUs: 'À propos',
    aboutTiqsey: 'À propos de Tiqsey',
    privacyPolicy: 'Politique de confidentialité',
    cookiePolicy: 'Politique des cookies',
    termsAndConditions: 'Conditions générales',
    platform: 'Plateforme',
    supportAndMedia: 'Assistance & Médias',
    myBookings: 'Mes Réservations',
    profile: 'Mon Profil',
    selectLanguage: 'Choisir la langue',
    selectCurrency: 'Choisir la devise',
    searchLanguagesPlaceholder: 'Rechercher une langue...',
    searchCurrenciesPlaceholder: 'Rechercher une devise...',
    noLanguagesFound: 'Aucune langue trouvée',
    noCurrenciesFound: 'Aucune devise trouvée'
  },
  nl: {
    heroEyebrow: 'ONTDEK. DROOM. BELEEF.',
    heroTitle1: 'Ontdek',
    heroTitle2: 'onvergetelijke',
    heroTitle3: 'ervaringen',
    heroTitle4: 'over de hele wereld',
    heroSubtitle: 'Handgekozen bestemmingen, unieke activiteiten en herinneringen voor het leven.',
    searchPlaceholder: 'Zoek attracties, steden of activiteiten...',
    searchBtn: 'Zoeken',
    popularDestinations: 'Populaire bestemmingen',
    topRatedAttractions: 'Populaire attracties',
    getTickets: 'Tickets bestellen',
    from: 'Vanaf',
    discoverMore: 'Meer laden',
    whyBook: 'Waarom boeken bij Tiqsey?',
    mobileTickets: 'Vertrouwd door duizenden',
    mobileTicketsSub: 'Ruim 12M+ tevreden klanten',
    unbeatableValue: 'Onverslaanbare waarde',
    unbeatableValueSub: 'Beste prijsgarantie',
    flexibleBooking: 'Flexibele boeking',
    flexibleBookingSub: 'Annuleer tot 24u van tevoren',
    navHome: 'Home',
    navHotDeals: 'Aanbiedingen',
    navAttractionsAndTours: 'Attracties & Musea',
    navThingsToDo: 'Dingen om te doen',
    navAboutUs: 'Over ons',
    navTravelBlog: 'Reisblog',
    navRegions: 'Regio\'s',
    navCities: 'Bestemmingen',
    navGoCityPass: 'Stadspas',
    navFavorites: 'Mijn Favorieten',
    navSignIn: 'Inloggen',
    navSignUp: 'Registreren',
    navMyAccount: 'Mijn Account',
    trustRating: '4.8/5 Beoordeling',
    securePayments: 'Veilig Betalen',
    securePaymentsSub: '100% Bescherming',
    instantBooking: 'Direct Boeken',
    instantBookingSub: 'Binnen seconden in huis',
    instantConfirmation: 'Directe Bevestiging',
    instantConfirmationSub: 'E-tickets direct ontvangen',
    freeCancellation: 'Gratis Annuleren',
    freeCancellationSub: 'Tot 24 uur van tevoren',
    bestPriceGuarantee: 'Beste Prijsgarantie',
    bestPriceGuaranteeSub: 'Gegarandeerd de scherpste prijs',
    secureBooking: 'Veilig Boeken',
    secureBookingSub: 'Uw gegevens zijn beschermd',
    specialOffers: 'Speciale Aanbiedingen',
    limitedStock: 'Beperkte voorraad beschikbaar',
    exploreWorldAttractions: 'Ontdek \'s werelds beste attracties & ervaringen',
    exploreWorldAttractionsSub: 'Boek tickets voor topattracties, tours en activiteiten in meer dan 180 landen.',
    adBannerHighlight: 'Boek nu en ontvang tot 30% korting op je volgende reis naar top bezienswaardigheden!',
    getBestDeals: 'Pak de Beste Deals',
    newsletterTitle: 'Blijf op de hoogte',
    newsletterSubtitle: 'Schrijf je in voor onze nieuwsbrief en ontvang een kortingscode voor je volgende boeking.',
    yourEmail: 'Je e-mailadres',
    subscribe: 'Inschrijven',
    subscribedSuccess: 'Bedankt voor je inschrijving! Bekijk je inbox.',
    regionLanguage: 'Regio & Taal',
    language: 'Taal',
    currency: 'Valuta',
    theme: 'Thema',
    wishlist: 'Verlanglijst',
    allRightsReserved: 'Alle rechten voorbehouden.',
    followUs: 'Volg ons',
    curatedSelection: 'Geselecteerd aanbod',
    support: 'Klantenservice',
    aboutUs: 'Over ons',
    aboutTiqsey: 'Over Tiqsey',
    privacyPolicy: 'Privacybeleid',
    cookiePolicy: 'Cookiebeleid',
    termsAndConditions: 'Algemene voorwaarden',
    platform: 'Platform',
    supportAndMedia: 'Klantenservice & Media',
    myBookings: 'Mijn Boekingen',
    profile: 'Mijn Profiel',
    selectLanguage: 'Kies taal',
    selectCurrency: 'Kies valuta',
    searchLanguagesPlaceholder: 'Zoek talen...',
    searchCurrenciesPlaceholder: 'Zoek valuta...',
    noLanguagesFound: 'Geen talen gevonden',
    noCurrenciesFound: 'Geen valuta gevonden'
  },
  es: {
    heroEyebrow: 'DESCUBRE. SUEÑA. EXPLORA.',
    heroTitle1: 'Explora',
    heroTitle2: 'experiencias',
    heroTitle3: 'inolvidables',
    heroTitle4: 'alrededor del mundo',
    heroSubtitle: 'Destinos seleccionados, actividades únicas y recuerdos para toda la vida.',
    searchPlaceholder: 'Buscar atracciones, ciudades o actividades...',
    searchBtn: 'Buscar',
    popularDestinations: 'Destinos populares',
    topRatedAttractions: 'Atracciones populares',
    getTickets: 'Conseguir entradas',
    from: 'Desde',
    discoverMore: 'Cargar más',
    whyBook: '¿Por qué reservar con Tiqsey?',
    mobileTickets: 'Confianza de miles',
    mobileTicketsSub: 'Más de 12M+ clientes felices',
    unbeatableValue: 'Valor imbatible',
    unbeatableValueSub: 'Garantía de mejor precio',
    flexibleBooking: 'Reserva Flexible',
    flexibleBookingSub: 'Cancela hasta 24h antes',
    navHome: 'Inicio',
    navHotDeals: 'Ofertas Especiales',
    navAttractionsAndTours: 'Atracciones y Museos',
    navThingsToDo: 'Cosas que hacer',
    navAboutUs: 'Sobre nosotros',
    navTravelBlog: 'Blog de viajes',
    navRegions: 'Regiones',
    navCities: 'Destinos',
    navGoCityPass: 'Pase de la Ciudad',
    navFavorites: 'Mis Favoritos',
    navSignIn: 'Iniciar sesión',
    navSignUp: 'Registrarse',
    navMyAccount: 'Mi Cuenta',
    trustRating: 'Valoración 4.8/5',
    securePayments: 'Pagos Seguros',
    securePaymentsSub: '100% Protección',
    instantBooking: 'Reserva Instantánea',
    instantBookingSub: 'Consíguelo en segundos',
    instantConfirmation: 'Confirmación Inmediata',
    instantConfirmationSub: 'Entradas electrónicas al instante',
    freeCancellation: 'Cancelación Gratuita',
    freeCancellationSub: 'Hasta 24 horas antes',
    bestPriceGuarantee: 'Garantía Mejor Precio',
    bestPriceGuaranteeSub: 'Igualamos el precio',
    secureBooking: 'Reserva Segura',
    secureBookingSub: 'Datos 100% protegidos',
    specialOffers: 'Ofertas Especiales',
    limitedStock: 'Últimas plazas disponibles',
    exploreWorldAttractions: 'Explora las mejores atracciones y experiencias del mundo',
    exploreWorldAttractionsSub: 'Reserva entradas para las mejores atracciones, tours y actividades en más de 180 países.',
    adBannerHighlight: '¡Reserva ahora y obtén hasta un 30% de descuento en tu próximo viaje!',
    getBestDeals: 'Obtener Mejores Ofertas',
    newsletterTitle: 'Mantente al día',
    newsletterSubtitle: 'Únete al boletín para recibir un descuento en tu próxima reserva.',
    yourEmail: 'Tu correo electrónico',
    subscribe: 'Suscribirse',
    subscribedSuccess: '¡Gracias por suscribirte! Revisa tu correo.',
    regionLanguage: 'Región e Idioma',
    language: 'Idioma',
    currency: 'Moneda',
    theme: 'Tema',
    wishlist: 'Lista de deseos',
    allRightsReserved: 'Todos los derechos reservados.',
    followUs: 'Síguenos',
    curatedSelection: 'Selección curada',
    support: 'Soporte',
    aboutUs: 'Sobre nosotros',
    aboutTiqsey: 'Acerca de Tiqsey',
    privacyPolicy: 'Política de privacidad',
    cookiePolicy: 'Política de cookies',
    termsAndConditions: 'Términos y condiciones',
    platform: 'Plataforma',
    supportAndMedia: 'Soporte y Medios',
    myBookings: 'Mis Reservas',
    profile: 'Mi Perfil',
    selectLanguage: 'Seleccionar idioma',
    selectCurrency: 'Seleccionar moneda',
    searchLanguagesPlaceholder: 'Buscar idiomas...',
    searchCurrenciesPlaceholder: 'Buscar monedas...',
    noLanguagesFound: 'No se encontraron idiomas',
    noCurrenciesFound: 'No se encontraron monedas'
  },
  pl: {
    heroEyebrow: 'ODKRYWAJ. MARZ. PODRÓŻUJ.',
    heroTitle1: 'Odkrywaj',
    heroTitle2: 'niezapomniane',
    heroTitle3: 'przygody',
    heroTitle4: 'na całym świecie',
    heroSubtitle: 'Wyselekcjonowane miejsca, unikalne atrakcje i wspomnienia na całe życie.',
    searchPlaceholder: 'Szukaj atrakcji, miast lub aktywności...',
    searchBtn: 'Szukaj',
    popularDestinations: 'Popularne kierunki',
    topRatedAttractions: 'Popularne atrakcje',
    getTickets: 'Kup bilety',
    from: 'Od',
    discoverMore: 'Załaduj więcej',
    whyBook: 'Dlaczego Tiqsey?',
    mobileTickets: 'Zaufanie tysięcy',
    mobileTicketsSub: 'Ponad 12M+ zadowolonych klientów',
    unbeatableValue: 'Bezkonkurencyjna cena',
    unbeatableValueSub: 'Gwarancja najniższej ceny',
    flexibleBooking: 'Elastyczna rezerwacja',
    flexibleBookingSub: 'Bezpłatne odwołanie do 24h',
    navHome: 'Strona główna',
    navHotDeals: 'Gorące Okazje',
    navAttractionsAndTours: 'Atrakcje i Muzea',
    navThingsToDo: 'Co warto zobaczyć',
    navAboutUs: 'O nas',
    navTravelBlog: 'Blog podróżniczy',
    navRegions: 'Regiony',
    navCities: 'Miasta',
    navGoCityPass: 'Karta Miejska',
    navFavorites: 'Ulubione',
    navSignIn: 'Zaloguj się',
    navSignUp: 'Zarejestruj się',
    navMyAccount: 'Moje Konto',
    trustRating: 'Ocena 4.8/5',
    securePayments: 'Bezpieczne Płatności',
    securePaymentsSub: '100% Ochrona',
    instantBooking: 'Natychmiastowa Rezerwacja',
    instantBookingSub: 'Bilety w kilka sekund',
    instantConfirmation: 'Błyskawiczne Potwierdzenie',
    instantConfirmationSub: 'E-bilety natychmiast na telefon',
    freeCancellation: 'Darmowe Odwołanie',
    freeCancellationSub: 'Do 24 godzin wcześniej',
    bestPriceGuarantee: 'Gwarancja Najlepszej Ceny',
    bestPriceGuaranteeSub: 'Wyrównujemy każdą cenę',
    secureBooking: 'Bezpieczna Rezerwacja',
    secureBookingSub: 'Twoje dane są chronione',
    specialOffers: 'Oferty Specjalne',
    limitedStock: 'Ostatnie wolne miejsca',
    exploreWorldAttractions: 'Odkryj najlepsze atrakcje i doświadczenia na świecie',
    exploreWorldAttractionsSub: 'Kup bilety na najlepsze atrakcje, wycieczki i aktywności w ponad 180 krajach.',
    adBannerHighlight: 'Zarezerwuj teraz i zgarnij do 30% zniżki na kolejną podróż!',
    getBestDeals: 'Odbierz Najlepsze Okazje',
    newsletterTitle: 'Bądź na bieżąco',
    newsletterSubtitle: 'Zapisz się do newslettera i odbierz kod rabatowy na kolejną rezerwację.',
    yourEmail: 'Twój adres e-mail',
    subscribe: 'Subskrybuj',
    subscribedSuccess: 'Dziękujemy za subskrypcję! Sprawdź swoją skrzynkę.',
    regionLanguage: 'Region i Język',
    language: 'Język',
    currency: 'Waluta',
    theme: 'Motyw',
    wishlist: 'Lista życzeń',
    allRightsReserved: 'Wszelkie prawa zastrzeżone.',
    followUs: 'Śledź nas',
    curatedSelection: 'Wyselekcjonowane atrakcje',
    support: 'Pomoc',
    aboutUs: 'O nas',
    aboutTiqsey: 'O Tiqsey',
    privacyPolicy: 'Polityka prywatności',
    cookiePolicy: 'Polityka plików cookie',
    termsAndConditions: 'Regulamin',
    platform: 'Platforma',
    supportAndMedia: 'Wsparcie & Media',
    myBookings: 'Moje Rezerwacje',
    profile: 'Mój Profil',
    selectLanguage: 'Wybierz język',
    selectCurrency: 'Wybierz walutę',
    searchLanguagesPlaceholder: 'Szukaj języków...',
    searchCurrenciesPlaceholder: 'Szukaj walut...',
    noLanguagesFound: 'Nie znaleziono języków',
    noCurrenciesFound: 'Nie znaleziono walut'
  },
  zh: {
    heroEyebrow: '探索 · 梦想 · 启程',
    heroTitle1: '探索',
    heroTitle2: '令人难忘的',
    heroTitle3: '精彩体验',
    heroTitle4: '畅游全球胜地',
    heroSubtitle: '精选全球热门目的地、独特活动与值得一生珍藏的旅行回忆。',
    searchPlaceholder: '搜索景点、城市或体验活动...',
    searchBtn: '搜索',
    popularDestinations: '热门目的地',
    topRatedAttractions: '热门景点',
    getTickets: '购买门票',
    from: '起',
    discoverMore: '加载更多',
    whyBook: '为什么选择 Tiqsey？',
    mobileTickets: '数万用户的信赖',
    mobileTicketsSub: '超过1200万+满意客户',
    unbeatableValue: '超值保证',
    unbeatableValueSub: '价格保证',
    flexibleBooking: '灵活预订',
    flexibleBookingSub: '提前24小时可免费取消',
    navHome: '首页',
    navHotDeals: '超值特惠',
    navAttractionsAndTours: '景点与博物馆',
    navThingsToDo: '必玩体验',
    navAboutUs: '关于我们',
    navTravelBlog: '旅行博客',
    navRegions: '地区',
    navCities: '目的地',
    navGoCityPass: '城市通票',
    navFavorites: '我的收藏',
    navSignIn: '登录',
    navSignUp: '注册',
    navMyAccount: '我的账户',
    trustRating: '4.8/5 好评',
    securePayments: '安全支付',
    securePaymentsSub: '100% 消费保障',
    instantBooking: '即时确认',
    instantBookingSub: '秒级获取电子票',
    instantConfirmation: '即时出票',
    instantConfirmationSub: '即刻获取电子门票',
    freeCancellation: '免费取消',
    freeCancellationSub: '出行前24小时可退',
    bestPriceGuarantee: '低价保证',
    bestPriceGuaranteeSub: '贵就赔',
    secureBooking: '安全预订',
    secureBookingSub: '全程保护您的数据隐私',
    specialOffers: '特别优惠',
    limitedStock: '仅剩少量余票',
    exploreWorldAttractions: '探索全球最佳景点与旅行体验',
    exploreWorldAttractionsSub: '预订覆盖180多个国家的顶级景点门票、导览与精彩体验。',
    adBannerHighlight: '立即预订，下次出行最高可享30%折扣！',
    getBestDeals: '获取最佳优惠',
    newsletterTitle: '订阅最新动态',
    newsletterSubtitle: '加入我们的时事通讯，获取下次预订的折扣码及旅行灵感。',
    yourEmail: '您的电子邮件地址',
    subscribe: '订阅',
    subscribedSuccess: '感谢您的订阅！请查收您的邮箱。',
    regionLanguage: '地区与语言',
    language: '语言',
    currency: '货币',
    theme: '主题',
    wishlist: '心愿单',
    allRightsReserved: '保留所有权利。',
    followUs: '关注我们',
    curatedSelection: '精选推荐',
    support: '帮助与支持',
    aboutUs: '关于我们',
    aboutTiqsey: '关于 Tiqsey',
    privacyPolicy: '隐私政策',
    cookiePolicy: 'Cookie 政策',
    termsAndConditions: '服务条款',
    platform: '平台',
    supportAndMedia: '客服与媒体',
    myBookings: '我的预订',
    profile: '个人资料',
    selectLanguage: '选择语言',
    selectCurrency: '选择货币',
    searchLanguagesPlaceholder: '搜索语言...',
    searchCurrenciesPlaceholder: '搜索货币...',
    noLanguagesFound: '未找到匹配语言',
    noCurrenciesFound: '未找到匹配货币'
  },
  it: {
    heroEyebrow: 'SCOPRI. SOGNA. ESPLORA.',
    heroTitle1: 'Esplora',
    heroTitle2: 'esperienze',
    heroTitle3: 'indimenticabili',
    heroTitle4: 'in tutto il mondo',
    heroSubtitle: 'Destinazioni selezionate, attività uniche e ricordi che durano per sempre.',
    searchPlaceholder: 'Cerca attrazioni, città o attività...',
    searchBtn: 'Cerca',
    popularDestinations: 'Destinazioni popolari',
    topRatedAttractions: 'Attrazioni popolari',
    getTickets: 'Acquista biglietti',
    from: 'Da',
    discoverMore: 'Carica altro',
    whyBook: 'Perché scegliere Tiqsey?',
    mobileTickets: 'Fiducia da migliaia',
    mobileTicketsSub: 'Più di 12M+ clienti felici',
    unbeatableValue: 'Valore imbattibile',
    unbeatableValueSub: 'Garanzia del miglior prezzo',
    flexibleBooking: 'Prenotazione Flessibile',
    flexibleBookingSub: 'Cancella fino a 24h prima',
    navHome: 'Home',
    navHotDeals: 'Offerte Speciali',
    navAttractionsAndTours: 'Attrazioni e Musei',
    navThingsToDo: 'Cose da fare',
    navAboutUs: 'Chi siamo',
    navTravelBlog: 'Blog di viaggi',
    navRegions: 'Regioni',
    navCities: 'Destinazioni',
    navGoCityPass: 'City Pass',
    navFavorites: 'I Miei Preferiti',
    navSignIn: 'Accedi',
    navSignUp: 'Registrati',
    navMyAccount: 'Il Mio Account',
    trustRating: 'Valutazione 4.8/5',
    securePayments: 'Pagamenti Sicuri',
    securePaymentsSub: 'Protezione al 100%',
    instantBooking: 'Prenotazione Istantanea',
    instantBookingSub: 'Ottienilo in pochi secondi',
    instantConfirmation: 'Conferma Immediata',
    instantConfirmationSub: 'Ricevi i biglietti all\'istante',
    freeCancellation: 'Cancellazione Gratuita',
    freeCancellationSub: 'Fino a 24 ore prima',
    bestPriceGuarantee: 'Miglior Prezzo Garantito',
    bestPriceGuaranteeSub: 'Tariffa imbattibile',
    secureBooking: 'Prenotazione Protetta',
    secureBookingSub: 'I tuoi dati sono al sicuro',
    specialOffers: 'Offerte Speciali',
    limitedStock: 'Disponibilità limitata',
    exploreWorldAttractions: 'Scopri le migliori attrazioni ed esperienze al mondo',
    exploreWorldAttractionsSub: 'Prenota biglietti per le migliori attrazioni, tour e attività in oltre 180 paesi.',
    adBannerHighlight: 'Prenota ora e ottieni fino al 30% di sconto sul tuo prossimo viaggio!',
    getBestDeals: 'Ottieni Migliori Offerte',
    newsletterTitle: 'Rimani aggiornato',
    newsletterSubtitle: 'Iscriviti alla newsletter per ricevere codici sconto esclusivi per le tue prossime prenotazioni.',
    yourEmail: 'Il tuo indirizzo email',
    subscribe: 'Iscriviti',
    subscribedSuccess: 'Grazie per l\'iscrizione! Controlla la tua email.',
    regionLanguage: 'Regione e Lingua',
    language: 'Lingua',
    currency: 'Valuta',
    theme: 'Tema',
    wishlist: 'Lista dei desideri',
    allRightsReserved: 'Tutti i diritti riservati.',
    followUs: 'Seguici',
    curatedSelection: 'Selezione curata',
    support: 'Assistenza',
    aboutUs: 'Chi siamo',
    aboutTiqsey: 'Informazioni su Tiqsey',
    privacyPolicy: 'Informativa sulla privacy',
    cookiePolicy: 'Politica sui cookie',
    termsAndConditions: 'Termini e condizioni',
    platform: 'Piattaforma',
    supportAndMedia: 'Assistenza & Media',
    myBookings: 'Le mie prenotazioni',
    profile: 'Il mio profilo',
    selectLanguage: 'Seleziona lingua',
    selectCurrency: 'Seleziona valuta',
    searchLanguagesPlaceholder: 'Cerca lingue...',
    searchCurrenciesPlaceholder: 'Cerca valute...',
    noLanguagesFound: 'Nessuna lingua trovata',
    noCurrenciesFound: 'Nessuna valuta trovata'
  },
  de: {
    heroEyebrow: 'ENTDECKEN. TRÄUMEN. ERLEBEN.',
    heroTitle1: 'Erlebe',
    heroTitle2: 'unvergessliche',
    heroTitle3: 'Momente',
    heroTitle4: 'auf der ganzen Welt',
    heroSubtitle: 'Handverlesene Reiseziele, einzigartige Aktivitäten und Erinnerungen für die Ewigkeit.',
    searchPlaceholder: 'Attraktionen, Städte oder Aktivitäten suchen...',
    searchBtn: 'Suchen',
    popularDestinations: 'Beliebte Reiseziele',
    topRatedAttractions: 'Beliebte Attraktionen',
    getTickets: 'Tickets sichern',
    from: 'Ab',
    discoverMore: 'Mehr laden',
    whyBook: 'Warum bei Tiqsey buchen?',
    mobileTickets: 'Vertraut von Tausenden',
    mobileTicketsSub: 'Über 12 Mio. zufriedene Kunden',
    unbeatableValue: 'Unschlagbarer Wert',
    unbeatableValueSub: 'Bestpreisgarantie',
    flexibleBooking: 'Flexible Buchung',
    flexibleBookingSub: 'Bis zu 24h vorher stornieren',
    navHome: 'Startseite',
    navHotDeals: 'Heiße Deals',
    navAttractionsAndTours: 'Attraktionen & Museen',
    navThingsToDo: 'Aktivitäten',
    navAboutUs: 'Über uns',
    navTravelBlog: 'Reiseblog',
    navRegions: 'Regionen',
    navCities: 'Reiseziele',
    navGoCityPass: 'City Pass',
    navFavorites: 'Meine Favoriten',
    navSignIn: 'Anmelden',
    navSignUp: 'Registrieren',
    navMyAccount: 'Mein Konto',
    trustRating: '4.8/5 Bewertung',
    securePayments: 'Sichere Zahlungen',
    securePaymentsSub: '100% Schutz',
    instantBooking: 'Sofortige Buchung',
    instantBookingSub: 'In Sekunden erhalten',
    instantConfirmation: 'Sofortige Bestätigung',
    instantConfirmationSub: 'E-Tickets sofort verfügbar',
    freeCancellation: 'Kostenlose Stornierung',
    freeCancellationSub: 'Bis zu 24 Stunden vorher',
    bestPriceGuarantee: 'Bestpreisgarantie',
    bestPriceGuaranteeSub: 'Wir garantieren den besten Preis',
    secureBooking: 'Sichere Buchung',
    secureBookingSub: 'Ihre Daten sind geschützt',
    specialOffers: 'Sonderangebote',
    limitedStock: 'Nur noch wenige Plätze verfügbar',
    exploreWorldAttractions: 'Entdecken Sie die weltbesten Attraktionen & Erlebnisse',
    exploreWorldAttractionsSub: 'Buchen Sie Tickets für Top-Attraktionen, Touren und Erlebnisse in über 180 Ländern.',
    adBannerHighlight: 'Buchen Sie jetzt und erhalten Sie bis zu 30% Rabatt auf Ihre nächste Reise!',
    getBestDeals: 'Beste Angebote sichern',
    newsletterTitle: 'Auf dem Laufenden bleiben',
    newsletterSubtitle: 'Melden Sie sich für unseren Newsletter an und erhalten Sie einen Rabattcode für Ihre nächste Buchung!',
    yourEmail: 'Ihre E-Mail-Adresse',
    subscribe: 'Abonnieren',
    subscribedSuccess: 'Vielen Dank für Ihre Anmeldung! Bitte prüfen Sie Ihr Postfach.',
    regionLanguage: 'Region & Sprache',
    language: 'Sprache',
    currency: 'Währung',
    theme: 'Design',
    wishlist: 'Wunschliste',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    followUs: 'Folgen Sie uns',
    curatedSelection: 'Kuratiertes Angebot',
    support: 'Kundenservice',
    aboutUs: 'Über uns',
    aboutTiqsey: 'Über Tiqsey',
    privacyPolicy: 'Datenschutzerklärung',
    cookiePolicy: 'Cookie-Richtlinie',
    termsAndConditions: 'AGB',
    platform: 'Plattform',
    supportAndMedia: 'Support & Medien',
    myBookings: 'Meine Buchungen',
    profile: 'Mein Profil',
    selectLanguage: 'Sprache auswählen',
    selectCurrency: 'Währung auswählen',
    searchLanguagesPlaceholder: 'Sprachen suchen...',
    searchCurrenciesPlaceholder: 'Währungen suchen...',
    noLanguagesFound: 'Keine Sprachen gefunden',
    noCurrenciesFound: 'Keine Währungen gefunden'
  },
  ru: {
    heroEyebrow: 'ОТКРЫВАЙ. МЕЧТАЙ. ПУТЕШЕСТВУЙ.',
    heroTitle1: 'Откройте',
    heroTitle2: 'незабываемые',
    heroTitle3: 'впечатления',
    heroTitle4: 'по всему миру',
    heroSubtitle: 'Лучшие направления, уникальные экскурсии и воспоминания на всю жизнь.',
    searchPlaceholder: 'Поиск достопримечательностей, городов и туров...',
    searchBtn: 'Найти',
    popularDestinations: 'Популярные направления',
    topRatedAttractions: 'Популярные места',
    getTickets: 'Купить билеты',
    from: 'От',
    discoverMore: 'Загрузить еще',
    whyBook: 'Почему Tiqsey?',
    mobileTickets: 'Доверие тысяч клиентов',
    mobileTicketsSub: 'Более 12 млн довольных путешественников',
    unbeatableValue: 'Лучшая цена',
    unbeatableValueSub: 'Гарантия лучшей цены',
    flexibleBooking: 'Гибкое бронирование',
    flexibleBookingSub: 'Отмена за 24 часа до начала',
    navHome: 'Главная',
    navHotDeals: 'Горящие предложения',
    navAttractionsAndTours: 'Достопримечательности и Музеи',
    navThingsToDo: 'Чем заняться',
    navAboutUs: 'О нас',
    navTravelBlog: 'Блог о путешествиях',
    navRegions: 'Регионы',
    navCities: 'Города',
    navGoCityPass: 'Городской абонемент',
    navFavorites: 'Избранное',
    navSignIn: 'Войти',
    navSignUp: 'Регистрация',
    navMyAccount: 'Мой аккаунт',
    trustRating: 'Рейтинг 4.8/5',
    securePayments: 'Безопасная оплата',
    securePaymentsSub: '100% Защита данных',
    instantBooking: 'Мгновенное бронирование',
    instantBookingSub: 'Получите билет за секунды',
    instantConfirmation: 'Мгновенное Подтверждение',
    instantConfirmationSub: 'Электронные билеты сразу на телефон',
    freeCancellation: 'Бесплатная Отмена',
    freeCancellationSub: 'За 24 часа до начала',
    bestPriceGuarantee: 'Гарантия Лучшей Цены',
    bestPriceGuaranteeSub: 'Снизим цену, если найдете дешевле',
    secureBooking: 'Безопасное Бронирование',
    secureBookingSub: 'Ваши данные под надежной защитой',
    specialOffers: 'Специальные акции',
    limitedStock: 'Осталось мало мест',
    exploreWorldAttractions: 'Лучшие достопримечательности и впечатления мира',
    exploreWorldAttractionsSub: 'Бронируйте билеты на главные аттракционы, экскурсии и музеи в более чем 180 странах.',
    adBannerHighlight: 'Забронируйте сейчас и получите скидку до 30% на следующую поездку!',
    getBestDeals: 'Получить скидку',
    newsletterTitle: 'Будьте в курсе',
    newsletterSubtitle: 'Подпишитесь на нашу рассылку и получите промокод на скидку для следующего бронирования.',
    yourEmail: 'Ваш email',
    subscribe: 'Подписаться',
    subscribedSuccess: 'Спасибо за подписку! Проверьте вашу почту.',
    regionLanguage: 'Регион и язык',
    language: 'Язык',
    currency: 'Валюта',
    theme: 'Тема',
    wishlist: 'Список желаний',
    allRightsReserved: 'Все права защищены.',
    followUs: 'Мы в соцсетях',
    curatedSelection: 'Отборные предложения',
    support: 'Поддержка',
    aboutUs: 'О нас',
    aboutTiqsey: 'О платформе Tiqsey',
    privacyPolicy: 'Политика конфиденциальности',
    cookiePolicy: 'Политика файлов cookie',
    termsAndConditions: 'Условия использования',
    platform: 'Платформа',
    supportAndMedia: 'Поддержка и СМИ',
    myBookings: 'Мои бронирования',
    profile: 'Мой профиль',
    selectLanguage: 'Выберите язык',
    selectCurrency: 'Выберите валюту',
    searchLanguagesPlaceholder: 'Поиск языков...',
    searchCurrenciesPlaceholder: 'Поиск валют...',
    noLanguagesFound: 'Языки не найдены',
    noCurrenciesFound: 'Валюты не найдены'
  },
  ro: {
    heroEyebrow: 'DESCOPERĂ. VISEAZĂ. EXPLOREAZĂ.',
    heroTitle1: 'Descoperă',
    heroTitle2: 'experiențe',
    heroTitle3: 'de neuitat',
    heroTitle4: 'în întreaga lume',
    heroSubtitle: 'Destinații alese cu grijă, activități unice și amintiri pentru o viață întreagă.',
    searchPlaceholder: 'Caută atracții, orașe sau activități...',
    searchBtn: 'Caută',
    popularDestinations: 'Destinații populare',
    topRatedAttractions: 'Atracții populare',
    getTickets: 'Cumpără bilete',
    from: 'De la',
    discoverMore: 'Încarcă mai mult',
    whyBook: 'De ce să rezervi cu Tiqsey?',
    mobileTickets: 'De încredere pentru mii de oameni',
    mobileTicketsSub: 'Peste 12M+ clienți mulțumiți',
    unbeatableValue: 'Preț imbatabil',
    unbeatableValueSub: 'Garanția celui mai bun preț',
    flexibleBooking: 'Rezervare flexibilă',
    flexibleBookingSub: 'Anulare gratuită cu până la 24h înainte',
    navHome: 'Acasă',
    navHotDeals: 'Ofertă Specială',
    navAttractionsAndTours: 'Atracții & Muzee',
    navThingsToDo: 'Activități',
    navAboutUs: 'Despre noi',
    navTravelBlog: 'Blog de călătorii',
    navRegions: 'Regiuni',
    navCities: 'Destinații',
    navGoCityPass: 'Pass Oraș',
    navFavorites: 'Favoritele Mele',
    navSignIn: 'Autentificare',
    navSignUp: 'Înregistrare',
    navMyAccount: 'Contul Meu',
    trustRating: 'Rating 4.8/5',
    securePayments: 'Plăți Securizate',
    securePaymentsSub: 'Protecție 100%',
    instantBooking: 'Rezervare Instantă',
    instantBookingSub: 'Primești biletul în câteva secunde',
    instantConfirmation: 'Confirmare Imediată',
    instantConfirmationSub: 'Bilete electronice instant',
    freeCancellation: 'Anulare Gratuită',
    freeCancellationSub: 'Până la 24 de ore înainte',
    bestPriceGuarantee: 'Garanția Prețului Minim',
    bestPriceGuaranteeSub: 'Garantăm cel mai bun tarif',
    secureBooking: 'Rezervare Sigură',
    secureBookingSub: 'Datele tale sunt protejate',
    specialOffers: 'Oferte Speciale',
    limitedStock: 'Locuri limitate rămase',
    exploreWorldAttractions: 'Explorează cele mai bune atracții și experiențe din lume',
    exploreWorldAttractionsSub: 'Rezervă bilete pentru atracții de top, tururi și activități în peste 180 de țări.',
    adBannerHighlight: 'Rezervă acum și primești până la 30% reducere la următoarea ta călătorie!',
    getBestDeals: 'Prinde Ofertele',
    newsletterTitle: 'Rămâi la curent',
    newsletterSubtitle: 'Abonați-vă la newsletter și primiți un cod de reducere pentru următoarea rezervare.',
    yourEmail: 'Adresa ta de email',
    subscribe: 'Abonare',
    subscribedSuccess: 'Mulțumim pentru abonare! Verifică-ți căsuța poștală.',
    regionLanguage: 'Regiune și Limbă',
    language: 'Limbă',
    currency: 'Monedă',
    theme: 'Temă',
    wishlist: 'Lista de dorințe',
    allRightsReserved: 'Toate drepturile rezervate.',
    followUs: 'Urmărește-ne',
    curatedSelection: 'Selecție recomandată',
    support: 'Suport',
    aboutUs: 'Despre noi',
    aboutTiqsey: 'Despre Tiqsey',
    privacyPolicy: 'Politica de confidențialitate',
    cookiePolicy: 'Politica privind cookie-urile',
    termsAndConditions: 'Termeni și condiții',
    platform: 'Platformă',
    supportAndMedia: 'Suport & Media',
    myBookings: 'Rezervările mele',
    profile: 'Profilul meu',
    selectLanguage: 'Selectează limba',
    selectCurrency: 'Selectează moneda',
    searchLanguagesPlaceholder: 'Caută limbi...',
    searchCurrenciesPlaceholder: 'Caută monede...',
    noLanguagesFound: 'Nu s-a găsit nicio limbă',
    noCurrenciesFound: 'Nu s-a găsit nicio monedă'
  },
  ar: {
    heroEyebrow: 'اكتشف · احلم · استكشف',
    heroTitle1: 'استكشف',
    heroTitle2: 'تجارب ساحرة',
    heroTitle3: 'لا تُنسى',
    heroTitle4: 'حول العالم',
    heroSubtitle: 'وجهات منتقاة بعناية، وأنشطة فريدة وذكريات تدوم مدى الحياة.',
    searchPlaceholder: 'ابحث عن المعالم السياحية أو المدن أو الأنشطة...',
    searchBtn: 'بحث',
    popularDestinations: 'وجهات شائعة',
    topRatedAttractions: 'أشهر المعالم السياحية',
    getTickets: 'حجز التذاكر',
    from: 'من',
    discoverMore: 'تحميل المزيد',
    whyBook: 'لماذا تختار Tiqsey؟',
    mobileTickets: 'موثوق من الآلاف',
    mobileTicketsSub: 'أكثر من 12 مليون عميل سعيد',
    unbeatableValue: 'قيمة لا تُضاهى',
    unbeatableValueSub: 'ضمان أفضل الأسعار',
    flexibleBooking: 'حجز مرن',
    flexibleBookingSub: 'إلغاء مجاني حتى 24 ساعة قبل الموعد',
    navHome: 'الرئيسية',
    navHotDeals: 'عروض ساخنة',
    navAttractionsAndTours: 'المعالم والمتاحف',
    navThingsToDo: 'الأنشطة الموصى بها',
    navAboutUs: 'من نحن',
    navTravelBlog: 'مدونة السفر',
    navRegions: 'المناطق',
    navCities: 'الوجهات',
    navGoCityPass: 'بطاقة المدينة',
    navFavorites: 'المفضلة لدي',
    navSignIn: 'تسجيل الدخول',
    navSignUp: 'إنشاء حساب',
    navMyAccount: 'حسابي',
    trustRating: 'تقييم 4.8/5',
    securePayments: 'دفع آمن',
    securePaymentsSub: 'حماية 100%',
    instantBooking: 'حجز فوري',
    instantBookingSub: 'احصل عليها خلال ثوانٍ',
    instantConfirmation: 'تأكيد فوري',
    instantConfirmationSub: 'احصل على التذاكر الإلكترونية فوراً',
    freeCancellation: 'إلغاء مجاني',
    freeCancellationSub: 'حتى 24 ساعة مقدماً',
    bestPriceGuarantee: 'ضمان أفضل الأسعار',
    bestPriceGuaranteeSub: 'نضمن لك أقل سعر متاح',
    secureBooking: 'حجز آمن ومشفر',
    secureBookingSub: 'بياناتك الشخصية محمية بالكامل',
    specialOffers: 'عروض خاصة',
    limitedStock: 'أماكن محدودة متبقية',
    exploreWorldAttractions: 'استكشف أفضل المعالم والتجارب السياحية في العالم',
    exploreWorldAttractionsSub: 'احجز تذاكر لأفضل المعالم والجولات والأنشطة السياحية في أكثر من 180 دولة.',
    adBannerHighlight: 'احجز الآن واحصل على خصم يصل إلى 30% على رحلتك القادمة!',
    getBestDeals: 'احصل على أفضل العروض',
    newsletterTitle: 'ابقَ على اطلاع',
    newsletterSubtitle: 'اشترك في نشرتنا البريدية واحصل على كود خصم لحجزك القادم وتلميحات سفر حصريّة.',
    yourEmail: 'بريدك الإلكتروني',
    subscribe: 'اشتراك',
    subscribedSuccess: 'شكراً لاشتراكك! تحقق من بريدك الإلكتروني.',
    regionLanguage: 'المنطقة واللغة',
    language: 'اللغة',
    currency: 'العملة',
    theme: 'المظهر',
    wishlist: 'قائمة الرغبات',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    followUs: 'تابعنا',
    curatedSelection: 'تشكيلة مختارة',
    support: 'الدعم',
    aboutUs: 'من نحن',
    aboutTiqsey: 'عن منصة Tiqsey',
    privacyPolicy: 'سياسة الخصوصية',
    cookiePolicy: 'سياسة ملفات تعريف الارتباط',
    termsAndConditions: 'الشروط والأحكام',
    platform: 'المنصة',
    supportAndMedia: 'الدعم والإعلام',
    myBookings: 'حجوزاتي',
    profile: 'ملفي الشخصي',
    selectLanguage: 'اختر اللغة',
    selectCurrency: 'اختر العملة',
    searchLanguagesPlaceholder: 'بحث في اللغات...',
    searchCurrenciesPlaceholder: 'بحث في العملات...',
    noLanguagesFound: 'لم يتم العثور على أي لغة',
    noCurrenciesFound: 'لم يتم العثور على أي عملة'
  },
  ja: {
    heroEyebrow: '発見する。夢見る。旅に出る。',
    heroTitle1: '忘れられない',
    heroTitle2: '素晴らしい体験を',
    heroTitle3: '世界中で',
    heroTitle4: '見つけよう',
    heroSubtitle: '世界中で厳選された人気スポット、特別なアクティビティ、そして一生の思い出を。',
    searchPlaceholder: '観光スポット、都市、アクティビティを検索...',
    searchBtn: '検索',
    popularDestinations: '人気の目的地',
    topRatedAttractions: '人気のアトラクション',
    getTickets: 'チケットを予約',
    from: '〜から',
    discoverMore: 'さらに読み込む',
    whyBook: 'Tiqseyが選ばれる理由',
    mobileTickets: '数万人に信頼されています',
    mobileTicketsSub: '1200万人以上の満足度の高いお客様',
    unbeatableValue: '比類のない価値',
    unbeatableValueSub: '最低価格保証',
    flexibleBooking: '柔軟な予約',
    flexibleBookingSub: '24時間前までキャンセル無料',
    navHome: 'ホーム',
    navHotDeals: 'お得な特売',
    navAttractionsAndTours: '観光スポット＆博物館',
    navThingsToDo: 'アクティビティ',
    navAboutUs: '会社概要',
    navTravelBlog: '旅のブログ',
    navRegions: '地域',
    navCities: '目的地',
    navGoCityPass: 'シティパス',
    navFavorites: 'お気に入り',
    navSignIn: 'ログイン',
    navSignUp: '新規登録',
    navMyAccount: 'マイアカウント',
    trustRating: '4.8/5 評価',
    securePayments: '安全な決済',
    securePaymentsSub: '100% 安全保障',
    instantBooking: '即時予約',
    instantBookingSub: '数秒で電子チケット発行',
    instantConfirmation: '即時確定',
    instantConfirmationSub: '即座にeチケットをお届け',
    freeCancellation: '無料キャンセル',
    freeCancellationSub: '24時間前まで可能',
    bestPriceGuarantee: '最安値保証',
    bestPriceGuaranteeSub: '安心のプライスマッチ',
    secureBooking: '安心・安全な予約',
    secureBookingSub: 'お客様のデータを安全に保護',
    specialOffers: '特別オファー',
    limitedStock: '残りわずか',
    exploreWorldAttractions: '世界最高の観光名所＆体験を発見',
    exploreWorldAttractionsSub: '180以上の国と地域で人気のアトラクション、ツアー、体験チケットを今すぐ予約。',
    adBannerHighlight: '今すぐ予約して、次回の旅行で最大30%オフの割引を手に入れましょう！',
    getBestDeals: 'ベストオファーを見る',
    newsletterTitle: '最新情報をお届け',
    newsletterSubtitle: 'メルマガに登録して、次回の予約で使える割引コードをゲットしましょう。',
    yourEmail: 'メールアドレス',
    subscribe: '登録する',
    subscribedSuccess: 'ご登録ありがとうございます！メールをご確認ください。',
    regionLanguage: '地域と言語',
    language: '言語',
    currency: '通貨',
    theme: 'テーマ',
    wishlist: 'ウィッシュリスト',
    allRightsReserved: 'All rights reserved.',
    followUs: '公式SNS',
    curatedSelection: '厳選セレクション',
    support: 'カスタマーサポート',
    aboutUs: '会社概要',
    aboutTiqsey: 'Tiqseyについて',
    privacyPolicy: 'プライバシーポリシー',
    cookiePolicy: 'クッキーポリシー',
    termsAndConditions: '利用規約',
    platform: 'プラットフォーム',
    supportAndMedia: 'サポート＆メディア',
    myBookings: '予約履歴',
    profile: 'マイプロフィール',
    selectLanguage: '言語を選択',
    selectCurrency: '通貨を選択',
    searchLanguagesPlaceholder: '言語を検索...',
    searchCurrenciesPlaceholder: '通貨を検索...',
    noLanguagesFound: '言語が見つかりませんでした',
    noCurrenciesFound: '通貨が見つかりませんでした'
  },
  th: {
    heroEyebrow: 'ค้นพบ · ใฝ่ฝัน · ออกเดินทาง',
    heroTitle1: 'สัมผัส',
    heroTitle2: 'ประสบการณ์อันน่าจดจำ',
    heroTitle3: 'ที่ไม่มีวันลืม',
    heroTitle4: 'ทั่วทุกมุมโลก',
    heroSubtitle: 'จุดหมายปลายทางที่คัดสรรมาอย่างดี กิจกรรมสุดพิเศษ และความทรงจำที่น่าประทับใจตลอดไป',
    searchPlaceholder: 'ค้นหาสถานที่ท่องเที่ยว เมือง หรือกิจกรรม...',
    searchBtn: 'ค้นหา',
    popularDestinations: 'จุดหมายปลายทางยอดนิยม',
    topRatedAttractions: 'สถานที่ท่องเที่ยวยอดนิยม',
    getTickets: 'จองตั๋วเข้าชม',
    from: 'เริ่มต้นที่',
    discoverMore: 'โหลดเพิ่มเติม',
    whyBook: 'ทำไมต้องจองกับ Tiqsey?',
    mobileTickets: 'ได้รับความไว้วางใจจากผู้ใช้นับแสนคน',
    mobileTicketsSub: 'ลูกค้าพึงพอใจกว่า 12 ล้านคน+',
    unbeatableValue: 'คุ้มค่าคุ้มราคา',
    unbeatableValueSub: 'การันตีราคาดีที่สุด',
    flexibleBooking: 'การจองที่ยืดหยุ่น',
    flexibleBookingSub: 'ยกเลิกฟรีล่วงหน้าสูงสุด 24 ชม.',
    navHome: 'หน้าแรก',
    navHotDeals: 'ดีลสุดฮอต',
    navAttractionsAndTours: 'สถานที่ท่องเที่ยว & พิพิธภัณฑ์',
    navThingsToDo: 'กิจกรรมน่าสนใจ',
    navAboutUs: 'เกี่ยวกับเรา',
    navTravelBlog: 'บล็อกท่องเที่ยว',
    navRegions: 'ภูมิภาค',
    navCities: 'เมืองปลายทาง',
    navGoCityPass: 'บัตรผ่านเมือง',
    navFavorites: 'รายการโปรดของฉัน',
    navSignIn: 'เข้าสู่ระบบ',
    navSignUp: 'สมัครสมาชิก',
    navMyAccount: 'บัญชีของฉัน',
    trustRating: 'คะแนนรีวิว 4.8/5',
    securePayments: 'ระบบชำระเงินปลอดภัย',
    securePaymentsSub: 'รับประกันความปลอดภัย 100%',
    instantBooking: 'ยืนยันการจองทันที',
    instantBookingSub: 'รับตั๋วในไม่กี่วินาที',
    instantConfirmation: 'ยืนยันทันที',
    instantConfirmationSub: 'รับตั๋วอิเล็กทรอนิกส์ได้ทันที',
    freeCancellation: 'ยกเลิกได้ฟรี',
    freeCancellationSub: 'ล่วงหน้าสูงสุด 24 ชั่วโมง',
    bestPriceGuarantee: 'การันตีราคาดีที่สุด',
    bestPriceGuaranteeSub: 'พร้อมปรับราคาให้เท่ากัน',
    secureBooking: 'ระบบจองปลอดภัย',
    secureBookingSub: 'ข้อมูลของคุณได้รับการปกป้องอย่างดี',
    specialOffers: 'ข้อเสนอพิเศษ',
    limitedStock: 'เหลือจำนวนจำกัด',
    exploreWorldAttractions: 'สำรวจสถานที่ท่องเที่ยวและประสบการณ์ที่ดีที่สุดในโลก',
    exploreWorldAttractionsSub: 'จองตั๋วสำหรับสถานที่ท่องเที่ยวยอดนิยม ทัวร์ และกิจกรรมในกว่า 180 ประเทศทั่วโลก',
    adBannerHighlight: 'จองตอนนี้และรับส่วนลดสูงสุด 30% สำหรับทริปถัดไปของคุณ!',
    getBestDeals: 'รับข้อเสนอดีที่สุด',
    newsletterTitle: 'เกาะติดทุกข่าวสาร',
    newsletterSubtitle: 'สมัครรับจดหมายข่าวของเราเพื่อรับโค้ดส่วนลดสำหรับการจองครั้งถัดไป',
    yourEmail: 'ที่อยู่อีเมลของคุณ',
    subscribe: 'ติดตาม',
    subscribedSuccess: 'ขอบคุณสำหรับการสมัคร! กรุณาตรวจสอบอีเมลของคุณ',
    regionLanguage: 'ภูมิภาคและภาษา',
    language: 'ภาษา',
    currency: 'สกุลเงิน',
    theme: 'ธีม',
    wishlist: 'รายการที่ชอบ',
    allRightsReserved: 'สงวนลิขสิทธิ์ทั้งหมด',
    followUs: 'ติดตามเรา',
    curatedSelection: 'คัดสรรมาเพื่อคุณ',
    support: 'ช่วยเหลือ',
    aboutUs: 'เกี่ยวกับเรา',
    aboutTiqsey: 'เกี่ยวกับ Tiqsey',
    privacyPolicy: 'นโยบายความเป็นส่วนตัว',
    cookiePolicy: 'นโยบายคุกกี้',
    termsAndConditions: 'ข้อกำหนดและเงื่อนไข',
    platform: 'แพลตฟอร์ม',
    supportAndMedia: 'ฝ่ายสนับสนุนและสื่อ',
    myBookings: 'การจองของฉัน',
    profile: 'โปรไฟล์ของฉัน',
    selectLanguage: 'เลือกภาษา',
    selectCurrency: 'เลือกสกุลเงิน',
    searchLanguagesPlaceholder: 'ค้นหาภาษา...',
    searchCurrenciesPlaceholder: 'ค้นหาสกุลเงิน...',
    noLanguagesFound: 'ไม่พบภาษาที่ค้นหา',
    noCurrenciesFound: 'ไม่พบสกุลเงินที่ค้นหา'
  }
};

export const SettingsProvider = ({ children }: { children: ReactNode }) => {
  const [detectedLocalCurrency, setDetectedLocalCurrency] = useState<Currency>(() => {
    const savedDetected = localStorage.getItem('tiqsey_detected_curr');
    if (savedDetected) {
      const found = CURRENCIES.find(c => c.code === savedDetected);
      if (found) return found;
    }
    const code = detectLocalCurrencyCode();
    return CURRENCIES.find(c => c.code === code) || CURRENCIES[0];
  });

  const [currency, setCurrency] = useState<Currency>(() => {
    const saved = localStorage.getItem('tiqsey_curr');
    if (saved) {
      return CURRENCIES.find(c => c.code === saved) || CURRENCIES[0];
    }
    const code = detectLocalCurrencyCode();
    const detected = CURRENCIES.find(c => c.code === code) || CURRENCIES[0];
    localStorage.setItem('tiqsey_curr', detected.code);
    return detected;
  });

  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('tiqsey_lang');
    if (saved) {
      const found = LANGUAGES.find(l => l.code === saved);
      if (found) return found;
    }
    try {
      const browserLang = (navigator.language || '').toLowerCase().slice(0, 2);
      const found = LANGUAGES.find(l => l.code === browserLang);
      if (found) return found;
    } catch (e) {
      // ignore
    }
    return LANGUAGES[0];
  });

  const [theme, setTheme] = useState<Theme>(() => {
    const saved = localStorage.getItem('tiqsey_theme') as Theme;
    return saved || 'light';
  });

  useEffect(() => {
    if (!localStorage.getItem('tiqsey_autodetected')) {
      const countryToCurrency: Record<string, string> = {
        US: 'USD', GB: 'GBP', AU: 'AUD', CA: 'CAD', CH: 'CHF', DK: 'DKK', NO: 'NOK',
        PL: 'PLN', SE: 'SEK', AE: 'AED', HU: 'HUF', SG: 'SGD', HK: 'HKD', JP: 'JPY',
        CO: 'COP', NZ: 'NZD', MY: 'MYR', CZ: 'CZK', MX: 'MXN', IN: 'INR', TH: 'THB',
        BR: 'BRL', AZ: 'AZN', BHD: 'BHD', BYN: 'BYN', CLP: 'CLP', CNY: 'CNY', ID: 'IDR',
        ILS: 'ILS', JOD: 'JOD', KRW: 'KRW', KWD: 'KWD', KZT: 'KZT', LAK: 'LAK', MNT: 'MNT',
        MOP: 'MOP', OMR: 'OMR', PHP: 'PHP', PKR: 'PKR', QAR: 'QAR', RUB: 'RUB', SAR: 'SAR',
        TRY: 'TRY', TWD: 'TWD', VND: 'VND', ZAR: 'ZAR',
        AT: 'EUR', BE: 'EUR', CY: 'EUR', EE: 'EUR', FI: 'EUR', FR: 'EUR', DE: 'EUR', GR: 'EUR',
        IE: 'EUR', IT: 'EUR', LV: 'EUR', LT: 'EUR', LU: 'EUR', MT: 'EUR', NL: 'EUR', PT: 'EUR',
        SK: 'EUR', SI: 'EUR', ES: 'EUR'
      };

      const handleDetectionSuccess = (currencyCode: string) => {
        const detectedCurr = CURRENCIES.find(c => c.code === currencyCode);
        if (detectedCurr) {
          setDetectedLocalCurrency(detectedCurr);
          localStorage.setItem('tiqsey_detected_curr', detectedCurr.code);
          
          if (!localStorage.getItem('tiqsey_curr_overridden')) {
            setCurrency(detectedCurr);
            localStorage.setItem('tiqsey_curr', detectedCurr.code);
          }
        }
        localStorage.setItem('tiqsey_autodetected', 'true');
      };

      const tryGeoServices = async () => {
        try {
          const res = await fetch('https://ipapi.co/json/');
          if (res.ok) {
            const data = await res.json();
            if (data.currency) {
              handleDetectionSuccess(data.currency);
              return;
            }
          }
        } catch (e) {
          console.warn('Geo service 1 (ipapi) failed:', e);
        }

        try {
          const res = await fetch('https://ip-api.com/json/');
          if (res.ok) {
            const data = await res.json();
            if (data.countryCode) {
              const mappedCurrency = countryToCurrency[data.countryCode.toUpperCase()];
              if (mappedCurrency) {
                handleDetectionSuccess(mappedCurrency);
                return;
              }
            }
          }
        } catch (e) {
          console.warn('Geo service 2 (ip-api) failed:', e);
        }

        localStorage.setItem('tiqsey_autodetected', 'true');
      };

      tryGeoServices();
    }
  }, []);

  useEffect(() => {
    const root = window.document.documentElement;
    root.lang = language.code;
    root.dir = language.dir || 'ltr';
  }, [language]);

  useEffect(() => {
    const root = window.document.documentElement;
    
    const applyTheme = (t: Theme) => {
      root.classList.remove('light', 'dark');
      
      if (t === 'system') {
        const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        root.classList.add(systemTheme);
      } else {
        root.classList.add(t);
      }
    };

    applyTheme(theme);

    if (theme === 'system') {
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
      const handleChange = () => applyTheme('system');
      mediaQuery.addEventListener('change', handleChange);
      return () => mediaQuery.removeEventListener('change', handleChange);
    }
  }, [theme]);

  const handleSetCurrency = (curr: Currency) => {
    setCurrency(curr);
    localStorage.setItem('tiqsey_curr', curr.code);
    localStorage.setItem('tiqsey_curr_overridden', 'true');
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('tiqsey_lang', lang.code);
  };

  const handleSetTheme = (t: Theme) => {
    setTheme(t);
    localStorage.setItem('tiqsey_theme', t);
  };

  const formatPrice = (price: number, baseCurrencyCode: string = 'EUR') => {
    const baseCurr = CURRENCIES.find(c => c.code === baseCurrencyCode) || CURRENCIES.find(c => c.code === 'EUR') || { rate: 1 };
    const priceInEur = price / baseCurr.rate;
    const converted = priceInEur * currency.rate;
    
    try {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: currency.code,
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      }).format(converted);
    } catch(e) {
      return `${currency.symbol}${converted.toFixed(2)}`;
    }
  };

  const t = (key: string, fallback?: string): string => {
    const langCode = language?.code || 'en';
    if (translations[langCode] && translations[langCode][key]) {
      return translations[langCode][key];
    }
    if (translations['en'] && translations['en'][key]) {
      return translations['en'][key];
    }
    return fallback || key;
  };

  return (
    <SettingsContext.Provider value={{ 
      currency, 
      detectedLocalCurrency,
      language,
      languages: LANGUAGES,
      theme,
      setCurrency: handleSetCurrency, 
      setLanguage: handleSetLanguage,
      setTheme: handleSetTheme,
      formatPrice, 
      t 
    }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return context;
};
