export const CURRENCY_FLAGS: Record<string, string> = {
  EUR: '🇪🇺',
  USD: '🇺🇸',
  GBP: '🇬🇧',
  AUD: '🇦🇺',
  CAD: '🇨🇦',
  CHF: '🇨🇭',
  DKK: '🇩🇰',
  NOK: '🇳🇴',
  PLN: '🇵🇱',
  SEK: '🇸🇪',
  AED: '🇦🇪',
  HUF: '🇭🇺',
  SGD: '🇸🇬',
  HKD: '🇭🇰',
  JPY: '🇯🇵',
  COP: '🇨🇴',
  NZD: '🇳🇿',
  MYR: '🇲🇾',
  CZK: '🇨🇿',
  MXN: '🇲🇽',
  INR: '🇮🇳',
  THB: '🇹🇭',
  BRL: '🇧🇷',
  AZN: '🇦🇿',
  BHD: '🇧🇭',
  BYN: '🇧🇾',
  CLP: '🇨🇱',
  CNY: '🇨🇳',
  IDR: '🇮🇩',
  ILS: '🇮🇱',
  JOD: '🇯🇴',
  KRW: '🇰🇷',
  KWD: '🇰🇼',
  KZT: '🇰🇿',
  LAK: '🇱🇦',
  MNT: '🇲🇳',
  MOP: '🇲🇴',
  OMR: '🇴🇲',
  PHP: '🇵🇭',
  PKR: '🇵🇰',
  QAR: '🇶🇦',
  RUB: '🇷🇺',
  SAR: '🇸🇦',
  TRY: '🇹🇷',
  TWD: '🇹🇼',
  VND: '🇻🇳',
  ZAR: '🇿🇦',
};

export const CURRENCY_COUNTRY_MAP: Record<string, string> = {
  EUR: 'eu',
  USD: 'us',
  GBP: 'gb',
  AUD: 'au',
  CAD: 'ca',
  CHF: 'ch',
  DKK: 'dk',
  NOK: 'no',
  PLN: 'pl',
  SEK: 'se',
  AED: 'ae',
  HUF: 'hu',
  SGD: 'sg',
  HKD: 'hk',
  JPY: 'jp',
  COP: 'co',
  NZD: 'nz',
  MYR: 'my',
  CZK: 'cz',
  MXN: 'mx',
  INR: 'in',
  THB: 'th',
  BRL: 'br',
  AZN: 'az',
  BHD: 'bh',
  BYN: 'by',
  CLP: 'cl',
  CNY: 'cn',
  IDR: 'id',
  ILS: 'il',
  JOD: 'jo',
  KRW: 'kr',
  KWD: 'kw',
  KZT: 'kz',
  LAK: 'la',
  MNT: 'mn',
  MOP: 'mo',
  OMR: 'om',
  PHP: 'ph',
  PKR: 'pk',
  QAR: 'qa',
  RUB: 'ru',
  SAR: 'sa',
  TRY: 'tr',
  TWD: 'tw',
  VND: 'vn',
  ZAR: 'za',
};

export function getCurrencyFlag(code: string): string {
  return CURRENCY_FLAGS[code.toUpperCase()] || '🏳️';
}

export function getCurrencyCountryCode(code: string): string {
  return CURRENCY_COUNTRY_MAP[code.toUpperCase()] || 'us';
}

