const fs = require('fs');
const path = require('path');

// New translation keys grouped by domain
const NEW_KEYS_EN = {
  discoverMore: 'Discover More',
  showLess: 'Show Less',
  takeALook: 'Take a look',
  experiences: 'Experiences',
  hotDealsOn: 'Hot Deals on',
  hotDealsSubtitle: "Grab the best deals on your dream experiences and create memories you'll cherish forever.",
  bookDeal: 'BOOK DEAL',
  save: 'Save',
  exclusiveOffersDeals: 'Exclusive Offers & Best Deals',
  activitiesPromotions: 'Activities Promotions',
  searchingExperiences: 'Searching amazing experiences...',
  recentSearches: 'Recent Searches',
  clearAll: 'Clear All',
  popularDestinations: 'Popular Destinations',
  topExperiences: 'Top Experiences',
  destinations: 'Destinations',
  activitiesAndExperiences: 'Activities & Experiences',
  exploreCity: 'Explore City',
  experiencesAvailable: 'Experiences available',
  popularDestination: 'Popular Destination',
  seeAllResultsFor: 'See all results for',
  search: 'Search',
  noActivitiesFound: 'No activities found',
  trySearchingElse: 'Try searching for something else like "Paris" or "Louvre"',
  activityNotFound: 'Activity Not Found',
  activityNotFoundDesc: 'The selected attraction could not be found or may have been removed.',
  backToActivities: 'Back to Activities',
  backToDetails: 'Back to details',
  provideBookingDetails: 'Provide Booking Details',
  selectVisitDate: '1. Select Visit Date',
  selectedTravelDate: 'Selected Travel Date',
  availableInstantConfirmation: 'Available & Instant Confirmation',
  available: 'Available',
  fillingFast: 'Filling Fast',
  selectTimeSlot: '2. Select Entry Time Slot',
  admissionWindowDesc: 'Please choose a preferred admission window. Keeping to your scheduled time ensures quick skip-the-line check-in.',
  bookingClosed: 'Booking Closed',
  soldOut: 'Sold Out',
  left: 'Left',
  numberOfTravelers: '3. Number of Travelers',
  adultTicket: 'Adult Ticket',
  adultTicketAge: 'Age 13–99 years',
  childTicket: 'Child Ticket',
  childTicketAge: 'Age 4–12 years (40% off)',
  requiredBookingDetails: '4. Required Booking Details',
  primaryTraveler: '(Primary Traveler)',
  travelerDetailsDesc: 'Your electronic skip-the-line barcode passes will be generated and registered to the traveler specified below.',
  selectCountryCode: 'Select Country Code',
  enterPhoneNumber: 'Enter Phone Number',
  specialRequestsPlaceholder: 'Any specific assistance requirements or general requests...',
  additionalPassengersDetails: '5. Additional Passengers Details',
  additionalPassengersDesc: 'Please provide the full names of the other travelers as printed on their passport or government ID.',
  dateOfBirthChild: 'Date of Birth (required for child ticket, age 4-12)',
  bookingSummary: 'Booking Summary',
  secureTicketPortal: 'Secure Ticket Portal',
  bookingFee: 'Booking Fee',
  taxesVat: 'Local Taxes & VAT',
  included: 'Included',
  promoDiscount: 'Promo Discount',
  promoCode: 'Promo Code',
  apply: 'Apply',
  totalPriceAllInc: 'Total Price (All Inc.)',
  secureRate: 'Secure Rate',
  currentlyUnavailable: 'Currently Unavailable',
  productNotAvailable: 'Product Currently Not Available',
  productNotAvailableDesc: 'We are sorry, but this tour/activity is currently unavailable for bookings. Please explore other attractions.',
  completingBooking: 'Completing Booking...',
  completeSecureBooking: 'Complete Secure Booking',
  sslEncrypted: 'SSL Encrypted',
  instantPass: 'Instant Pass',
  bestseller: 'Bestseller',
  trending: 'Trending',
  productId: 'Product ID',
  shareLink: 'Share Link',
  selectPackageOptions: 'Select Package Options',
  mostBooked: '★ MOST BOOKED',
  hideDetails: 'HIDE DETAILS',
  showDetails: 'SHOW DETAILS',
  packageDetailsInfo: 'Package Details & Information',
  agePolicy: 'Age Policy',
  importantNotes: 'Important Notes',
  priceIncludes: 'Price Includes',
  otherRelevantDetails: 'Other Relevant Details',
  startingFrom: 'Starting from',
  off: 'Off',
  guestReviewsSubtitle: 'Genuine feedback from verified travelers who booked this experience',
  closeForm: 'Close Form',
  shareYourExperience: 'Share Your Experience',
  reviewPostedSuccess: 'Review posted successfully! Your rating has been logged in real-time.',
  yourFullName: 'Your Full Name',
  ratingSelectStars: 'Rating (Select Stars)',
  yourComment: 'Your Comment',
  reviewPlaceholder: 'Describe your tour details, guides, entry details, or audio headsets...',
  postVerifiedReview: 'Post Verified Review',
  verifiedLogs: 'Verified Logs',
  quickView: 'Quick View:',
  stars: 'Stars',
  verifiedGuest: 'Verified Guest',
  viewFewerReviews: 'View Fewer Reviews',
  readAllReviews: 'Read All Reviews',
  thankYouForOrder: 'Thank you for your order!',
  orderProcessingNotice: 'Your order is being processed and it will take up to 30 minutes to confirm.',
  explorerTicketPass: 'Explorer Ticket Pass',
  pnrNumber: 'PNR Number:',
  reservationDate: 'Reservation Date',
  admissionTime: 'Admission Time',
  participants: 'Participants',
  additionalPassengers: 'Additional Passengers',
  amountProcessed: 'Amount Processed',
  passStatus: 'Pass Status',
  activeAdmissionQR: 'Active admission QR',
  ticketPassUUID: 'Ticket pass UUID:',
  downloadTicket: 'Download Ticket',
  viewMyTickets: 'View My Tickets',
  continueTraveling: 'Continue Traveling',
  activityLinkUrl: 'Activity Link URL',
  copy: 'Copy',
  copied: 'Copied',
  quickShare: 'Quick Share',
  scanQrMobile: 'Scan QR code to open on mobile',
  exploreTheWorld: 'Explore the World',
  allExperiencesInOnePlace: 'All Experiences in One Place',
  filters: 'Filters',
  regions: 'Regions',
  reset: 'Reset',
  recommended: 'Recommended',
  priceLowHigh: 'Price: Low to High',
  priceHighLow: 'Price: High to Low',
  topRatedFirst: 'Top Rated First',
  highestDiscountFirst: 'Highest Discount First',
  showingOutOfExperiences: 'Showing {shown} out of {total} listed experiences',
  foundDiscountedPasses: 'Found {count} discounted passes',
  noMatchingExperiences: 'No matching experiences',
  noMatchingExperiencesDesc: "We couldn't find any activities matching your filters. Try adjusting your search query or choosing another category or city.",
  clearAllFilters: 'Clear all filters',
  returnToExplore: 'Return to Explore',
  curatedExperiences: 'Curated Experiences',
  availableTours: 'Available Tours',
  curatedOptions: '{count} Curated Options',
  qualityAssurance: 'Quality Assurance',
  topRatedClass: 'Top-Rated {rating}★ Class',
  startingRate: 'Starting Rate',
  recommendedMatches: 'Recommended Matches',
  topGuestRatingsFirst: 'Top Guest Ratings First',
  activeFilters: 'Active:',
  neighborhoodSubRegion: 'Neighborhood / Sub-Region',
  themeCategory: 'Theme & Category',
  priceSpectrum: 'Price Spectrum',
  budgetOption: 'Budget (≤$20)',
  midTierOption: 'Mid-Tier ($20–$50)',
  premiumOption: 'Premium ($50+)',
  guestReviewsRatings: 'Guest Reviews & Ratings',
  andAbove: 'and above',
  signInRequired: 'Sign In Required',
  signInRequiredWishlistDesc: 'Please sign in to your Tiqsey account to access and sync your saved wishlist items across all devices.',
  signInRequiredBookingsDesc: 'Please sign in to view your bookings, download ticket vouchers, and manage your upcoming reservations.',
  returnToHome: 'Return to Home',
  shareList: 'Share List',
  copiedLink: 'Copied Link!',
  savedWishlist: 'Saved Wishlist',
  savedExperiences: 'Saved Experiences',
  estimatedValue: 'Estimated Value',
  potentialSavings: 'Potential Savings',
  hotDeals: 'Hot Deals',
  searchSavedTickets: 'Search saved tickets...',
  noSavedExperiences: 'No saved experiences yet',
  emptyWishlistTitle: 'Your wishlist is empty',
  emptyWishlistDesc: 'Start searching or exploring. Click the heart icon on any attraction card to catalog your favorites right here!',
  findAttractions: 'Find Attractions',
  selectedItems: 'Selected Items',
  confirmClearWishlist: 'Are you sure you want to clear your entire wishlist?',
  exploreSavedFavorites: 'Explore Saved Favorites',
  myBookingsAndTickets: 'My Bookings & Tickets',
  myBookingsHeroDesc: 'Manage and view all your confirmed vouchers and upcoming travel reservations.',
  upcomingAndActive: 'Upcoming & Active',
  pastAndHistory: 'Past & History',
  leadGuest: 'Lead Guest',
  amountPaid: 'Amount Paid',
  noUpcomingBookings: 'No upcoming bookings found',
  noUpcomingBookingsDesc: 'Explore activities and discover your next unforgettable experience.',
  browseAttractions: 'Browse Attractions',
  chooseAvatar: 'Choose an Avatar',
  chooseAvatarDesc: 'Select your favorite travel avatar to personalize your profile across reviews and tickets.',
  saveAvatar: 'Save Avatar',
  cancel: 'Cancel',
  avatarUpdated: 'Avatar updated successfully!',
  welcomeBack: 'Welcome back',
  signInSubtitleModal: 'Sign in to manage your bookings, wishlist, and ticket vouchers.',
  continueWithGoogle: 'Continue with Google',
  orDivider: 'OR',
  createAccountDesc: 'Join Tiqsey to start exploring and booking your next adventure.',
  alreadyAccountSignIn: 'Already have an account? Sign in',
  dontHaveAccount: "Don't have an account yet?",
  createOneNow: 'Create an account',
  discoverTheWorld: 'Discover the world. One experience at a time.',
  aboutHeroDesc: "At Tiqsey, we believe every journey should be unforgettable. We make it easy to discover, book and enjoy the world's best attractions, tours and activities.",
  trustedByMillions: 'Trusted by millions',
  trustedByMillionsDesc: 'Join thousands of happy travelers worldwide.',
  instantConfirmationTitle: 'Instant confirmation',
  instantConfirmationDesc: 'Get your tickets instantly and skip the queues.',
  support247: '24/7 Support',
  support247Desc: "We're here for you anytime, anywhere.",
  ourStory: 'OUR STORY',
  ourStorySubtitle: 'Tiqsey was founded with a simple mission: to help travelers explore the world with ease and confidence.',
  ourStoryDesc: "We know travel is more than just visiting new places — it's about creating memories that last a lifetime. That's why we partner with trusted local operators to bring you handpicked experiences at the best prices, with instant booking and real human support.",
  ourStoryFooter: 'From iconic landmarks to hidden gems, we make every experience count.',
  ourMission: 'OUR MISSION',
  ourMissionDesc: 'To make travel more accessible and enjoyable for everyone by offering a wide range of curated experiences with transparency, convenience and outstanding value.',
  ourVision: 'OUR VISION',
  ourVisionDesc: "To be the world's most trusted platform for travel experiences, inspiring people to explore more and create unforgettable memories.",
  whyChooseTiqsey: 'WHY CHOOSE TIQSEY?',
  wideSelection: 'Wide Selection',
  wideSelectionDesc: 'Thousands of activities in 30+ countries and growing every day.',
  topRatedExp: 'Top Rated Experiences',
  topRatedExpDesc: 'Handpicked experiences rated by real travelers like you.',
  secureBookingDesc: 'Your data is safe with us. We use industry-leading security.',
  countries: 'Countries',
  averageRating: 'Average Rating',
  happyTravelers: 'Happy Travelers',
  exploreAllDestinations: 'Explore All Destinations',
  readyToExploreWorld: 'Ready to explore the world?',
  readyToExploreWorldDesc: 'Find the best attractions, tours and activities and make your next trip unforgettable.',
  blogHeroEyebrow: 'TIQSEY CHRONICLES',
  blogHeroTitle: 'Stories, Guides & Inspiration',
  blogHeroSubtitle: 'Discover insider travel tips, destination spotlights, and cultural stories curated by global explorers.',
  searchArticlesPlaceholder: 'Search articles, destinations, or tips...',
  featuredStory: 'Featured Story',
  readStory: 'Read Story',
  minRead: 'min read',
  publishedOn: 'Published on',
  shareArticle: 'Share Article',
  copiedToClipboard: 'Link copied to clipboard!',
  backToBlog: 'Back to Blog',
  relatedArticles: 'Related Articles',
  comments: 'Comments',
  leaveAReply: 'Leave a Reply',
  noArticlesFound: 'No articles found',
  exploreOtherStories: 'Explore Other Stories',
  footerTagline: 'Making culture accessible to everyone. We help you find and book the best tickets for museums and attractions worldwide.',
  footerPlatform: 'Platform',
  adminCommandCenter: 'Admin Command Center',
  aboutAndPolicies: 'About & Policies',
  subscribeNewsletter: 'Subscribe to our newsletter',
  newsletterDesc: 'Get the latest travel deals and inspiration straight to your inbox.',
  enterEmailPlaceholder: 'Enter your email',
  thankYouSubscribing: '✓ Thank you for subscribing!',
  trustedAndSecure: 'Trusted & Secure',
  weAccept: 'We Accept',
  somethingWentWrong: 'Something went wrong',
  somethingWentWrongDesc: "We couldn't load this information right now. Please try again later.",
  tryAgain: 'Try Again',
  refreshPage: 'Refresh Page',
  catAll: 'All',
  catTravelGuides: 'Travel Guides',
  catTipsTricks: 'Tips & Tricks',
  catTopAttractions: 'Top Attractions',
  catCultureHistory: 'Culture & History',
  catFoodDrink: 'Food & Drink',
  view: 'View',
  history: 'History',
  jumpBackFavorites: 'Jump back into your favorites',
  clearHistory: 'Clear history',
  instant: 'Instant',
  searchLanguages: 'Search languages...',
  searchCurrencies: 'Search currencies...',
  resetSearch: 'Reset search',
  searchResults: 'Search Results',
  topCurrencies: 'Top currencies',
  languageDisclaimer: 'Changing the language will translate supported UI elements and content across Tiqsey.',
  currencyDisclaimer: 'Where applicable, prices will be converted and shown in the currency you select. The currency you pay in may differ based on your reservation.',
};

module.exports = { NEW_KEYS_EN };
